### ISSUE TITLE
Separate config files

### ISSUE THREAD

**Issue by Iniquitatis** [Youda008/DoomRunner#1]
Hey, nice project! Finally, I can get rid of multitudes of *.bat files. :)
But let's get straight to the request: it would be pretty nice if the launcher could support separate configuration files without specifying something like _-config Blah.ini_.
Thanks!

**Comment by Youda008** [comment]
Hi. You mean like `gzdoom.exe -config blah.ini`? I didn't even know it is possible lol. Can be done, sure. Just out of curiosity, why do you need that?

**Comment by Iniquitatis** [comment]
Yes, it is indeed possible. :)
Well, different mods and "playlists" often need its own configurations, simple example: some modern-style mod needs vertical mouse aiming, while another, vanilla-style, does not need it at all.
So switching between 10-15 gameplay mods (and I'm not even talking about TCs) can become pretty painful, where each one of them requires to delve into the settings menu.
Also, there's conflicts between control mappings, etc.

**Comment by Youda008** [comment]
Yea, that makes sense. Will definitely be in the next version.
Can i count that all the different config files are in the same directory as the engine? Or would you like to load them even from different directories?

**Comment by Iniquitatis** [comment]
Either of these two would be good, so whatever makes more sense from your perspective. :)

(But the first thing that comes to mind is some path selector/text field, so both of your options would be possible.)

**Comment by Youda008** [comment]
Hi. Sorry for that delay, i had final exams at university. Now the beta version is ready and this feature is there. It detects all config files inside selected engine's folder and let's you chose one of them.

**Comment by Iniquitatis** [comment]
Thanks a lot! I'll check this ASAP.
