### ISSUE TITLE
Feature Request: Default Engine

### ISSUE THREAD

**Issue by Llorean** [Youda008/DoomRunner#101]
99.9% of the time, I just want to use my most current version of gzDoom, which I'll always overwrite the previous version with. But I have a couple presets that use another engine, so now every time I add a preset I have to manually select the engine in the dropdown. It'd be wonderful if I could somehow just tag one engine as the default, and have it always use that engine unless I manually select another engine. I know it's a minor thing, but it seems like it'd be a relatively small quality of life upgrade that'd be quite nice. It could be as simple as just having a checkbox to "default to the topmost engine in the list if none selected."

**Comment by Youda008** [comment]
I think i have a prototype ready, i will do some more testing and if everything goes well, it should go out soon.
