### ISSUE TITLE
Ubuntu 22.04.2 LTS: Attempting to download libraries ends in an error.

### ISSUE THREAD

**Issue by PzKpfw6** [Youda008/DoomRunner#104]
While attempting to install libqt5core, libqt5gui, libqt5widgets, and using the suggested "sudo apt install lib[name]", all I get is a "E: Unable to locate package lib[name]" error.
This is how it looks:
sudo apt install lib[name]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package lib[name]
![Screenshot from 2023-05-12 21-31-54](https://github.com/Youda008/DoomRunner/assets/125630251/e64b613e-536f-44e7-bb30-0676c211838a)

Any way to fix it? Even the links to the libraries will do.

**Comment by Youda008** [comment]
The libraries in Ubuntu are currently called

- libqt5core5a
- libqt5gui5
- libqt5widgets5
- libqt5network5

These names are unfortunatelly distribution-specific and they also change in time (they were called differently in Ubuntu 18), so i cannot provide exact instructions in README, sorry.

**Comment by PzKpfw6** [comment]
I understood that this is a distro related issue, and glad that you could give me the names for the latest LTS Ubuntu. Thanks man, it work great! I can finally use DoomRunner instead of ZDL. Have a great day.
