### ISSUE TITLE
Engine/IWAD marked as default () no longer exists

### ISSUE THREAD

**Issue by muppi090909** [Youda008/DoomRunner#106]
![image](https://github.com/Youda008/DoomRunner/assets/79302850/d72b2927-6f39-40f1-959a-aa3fd425f4ab)
I am quite sure it is just me not setting an option, but I cant find it.

**Comment by Youda008** [comment]
No, that's a bug. If it's empty, it should not be searched for.

**Comment by Youda008** [comment]
For now you can get rid of it by right-clicking one of the engines and selecting "set as default"

**Comment by muppi090909** [comment]
> For now you can get rid of it by right-clicking one of the engines and selecting "set as default"

Thanks !

**Comment by Youda008** [comment]
Fixed in master branch.
