### ISSUE TITLE
Missing window icon on Linux

### ISSUE THREAD

**Issue by mbugni** [Youda008/DoomRunner#108]
The upper-left corner icon is missing on Linux. I'm not a Qt expert, but I suppose that the .ico format is not supported. I attached a set of Doom Runner .png icons just in case.

![missing-icon](https://github.com/Youda008/DoomRunner/assets/14926724/2b90e5ed-4703-4b46-a783-517f4a9761c1)

[doomrunner-icons.zip](https://github.com/Youda008/DoomRunner/files/11853050/doomrunner-icons.zip)

**Comment by Youda008** [comment]
Originally i didn't know how, but i see Qt has finally updated their guide, so i can do this now.

**Comment by mbugni** [comment]
It seems fixed now (on `master` branch`).

![missing-icon-fixed](https://github.com/Youda008/DoomRunner/assets/14926724/c6a73ede-9f91-406b-ba82-4b08096a7cd4)

**Comment by Youda008** [comment]
Fixed and released.
