### ISSUE TITLE
[Request] Copy/erase function for "Current" preset

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#11]
Make it possible to copy over all settings (engine, IWAD, map pack, config, mods) from any preset to "Current". Any new preset transfer to "Current" would completely overwrite any existing entries.

**Comment by Youda008** [comment]
But why?

**Comment by Caiuzx** [comment]
however a function to delete a preset as in zdl would come in handy.

**Comment by Youda008** [comment]
The "Current" preset will be removed completely, because i see it's only confusing for people and makes them use it the wrong way.
