### ISSUE TITLE
[Feature Request] Add support for enable/disabling multipule items that are highlighted

### ISSUE THREAD

**Issue by Underqualified-Gunman** [Youda008/DoomRunner#112]
currently when multiple items are highlighted you can move them around or delete them but press the check to disable will not mimic this behavior. would be quite handy for diabling large parts of a modlist to trouble shoot issues

**Comment by Youda008** [comment]
That is probably impossible using mouse click, but you can press Spacebar and it should do what you want.

**Comment by Youda008** [comment]
Can i close this? Is the spacebar enough for you, or do you still want to tick multiple items with mouse?

**Comment by Underqualified-Gunman** [comment]
spacebars fine for me. just forgot to respond.

**Comment by Youda008** [comment]
Ok, thank you.
