### ISSUE TITLE
Nix/NixOS instructions

### ISSUE THREAD

**Issue by keenanweaver** [Youda008/DoomRunner#114]
Howdy,

I created a [Nix package](https://search.nixos.org/packages?channel=unstable&show=doomrunner&from=0&size=50&sort=relevance&type=packages&query=doomrunner) for your project. It's currently in the unstable branch, but it will eventually make its way to the stable channel.

If you want to put this in your README.md, here are the instructions:

### Nix on non-NixOS

> 1. Install the package with `nix-env -iA nixpkgs.doomrunner`

### NixOS

> 1. Add one of the following to your configuration.nix
> ``` nix
>   environment.systemPackages = with pkgs; [
>     doomrunner
>   ];
> ```
> 
> or 
> 
> ``` nix
>   users.users.yourUserName.packages = with pkgs; [
>     doomrunner
>   ];
> ```
> 2. Rebuild the system with `nixos-rebuild`

**Comment by Youda008** [comment]
Awesome man. Thanks a lot for making DoomRunner accessible to more users. I will definitely add this to README once i finish the work on the 1.8.0.

**Comment by Youda008** [comment]
Done, thank you.
