### ISSUE TITLE
[+dmflags] give the opportunity  to remove the +dmflags command from command line.

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#119]
with doomrunner i tested :
+raze for duke nukem 3d , blood , shadow warrior - ok
+qzandronum, zandronum - ok
+edge-engine - no
+dsda doom 0.62 - no

no because these engines , do not accept the +dmflags command, with load a map or mods
can it be removed from the command line ? 
thanks !

**Comment by Youda008** [comment]
Just clear the DM flags in the "Detailed gameplay options" dialog, and the `+dmflags` parameter will disappear.

**Comment by Caiuzx** [comment]
thanks , the engines run perfectly 👯

**Comment by Youda008** [comment]
Alright then.
Anniversary 100th solved issue 🎉🎂
