### ISSUE TITLE
[bug]Selected map deselects when I close doom runner

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#12]
Also if i create a preset , the selected map (wad) that i play , i have to re-select it

**Comment by Youda008** [comment]
Well, it's not a bug, it has always been like that. Personally i didn't see the need to save a map selection, because everytime i launch it, i want to play something else. But i can make it save, it's not a problem.

Question is, whether to
1. save the map to preset and then restore it from there when preset is selected,
2. or save the map on quit and then restore it on launch.
Can't have both, that will not work, you must decide.

**Comment by Caiuzx** [comment]
why don't you play megawads? do you play doom in single map?
I choose the first one, because when I can play something else I create a new preset. For example a single map or a megawads that takes time to finish it.
But if I want to stop and play a megawads I have the preset ready and just click on it with the map already set.
You can include everything in the preset with the words:
>map :
>mod :

**Comment by Youda008** [comment]
In the meantime i implemented option 1. but if i get more opinions from more people, i will change it in the future.

**Comment by Caiuzx** [comment]
> 
> 
> In the meantime i implemented option 2. but if i get more opinions from more people, i will change it in the future.

you didn't want to implement option 1?
**why don't you put both?**
Does option 2 work that when you exit to a preset save the map?

**Comment by Youda008** [comment]
Because i don't want the map to change, when i change preset. For me preset means a mod files and i want to be able to switch mod independently from maps. When i release, i will ask more people on forum and then make a decision according to majority opinion.

**Comment by Caiuzx** [comment]
> 
> 
> Because i don't want the map to change, when i change preset. For me preset means a mod files and i want to be able to switch mod independently from maps. When i release, i will ask more people on forum and then make a decision according to majority opinion.

ok thanks

**Comment by Youda008** [comment]
So after the feedback at DoomWorld forum i made the selected maps part of preset, so it will be saved to and restored from presets in next release.
