### ISSUE TITLE
Tooltip about sv_cheats is incorrect for GZDoom versions beyond 4.9.0

### ISSUE THREAD

**Issue by nashmuhandes** [Youda008/DoomRunner#120]
As of GZDoom ~~4.10~~ 4.9.0, the CVar is no longer latched and will take effect immediately

EDIT: updated my post to specify the actual version of GZDoom where it changed

**Comment by Youda008** [comment]
Ok, thanks for reporting.

**Comment by Youda008** [comment]
Do you know in which version it changed?

**Comment by nashmuhandes** [comment]
> Do you know in which version it changed?

GZDoom 4.9.0 was when it was changed. Source: https://forum.zdoom.org/viewtopic.php?p=1231478&hilit=latch+flag+sv_cheats#p1231478

**Comment by Youda008** [comment]
Fixed. Release will hopefully be soon.
