### ISSUE TITLE
[BUG] Custom command line option does not work with spaces

### ISSUE THREAD

**Issue by proydoha** [Youda008/DoomRunner#121]
When adding custom command line options to 'Add mods' column it seems like anything without spaces works (`-nomonsters` for example) but if I'm adding anything with a space in it it seemingly gets ignored (for example `+map map02` will load you into main menu instead of map02)

'Final launch command' looks correct but something is not working right.

'Additional command line arguments' still working as usual so that one gets added correctly

**Comment by Youda008** [comment]
Ah, forgot about this. Will fix it in the next version. Until then you have to split it into 2 entries.

**Comment by Youda008** [comment]
fixed
