### ISSUE TITLE
[Feature] Open engine location

### ISSUE THREAD

**Issue by proydoha** [Youda008/DoomRunner#122]
Similar to 'Open file location' but opens selected engine folder instead.

Not sure where to put it in interface. Maybe into same dropdown although it doesn't make much sense for it to be there ( ? )

**Comment by Youda008** [comment]
You mean from the main window or from the Setup dialog?

**Comment by proydoha** [comment]
From main window. That's why I've said that I'm not sure where it should be.

There are things that you may want to access in an engine folder (at least when its set as a portable version): screenshots, config files, log files, savegame names if you're planning to load into one from command line parameters. It would be handy to be able to go there from the launcher.

**Comment by Youda008** [comment]
Hmm 🤔 You cannot right-click a drop-down list item, there would have to be yet another button.
Or i can make the "Browse Save files" button on the second tab always open the engine's data directory, even when the line is empty.

**Comment by proydoha** [comment]
"Browse save files" shouldn't always open engine folder because when GZD is set to not be portable it'll keep its saves somewhere in documents. At least on Windows.

**Comment by Youda008** [comment]
That's why i said "engine's data directory" which is something different than "engine"s executable/binary directory"

**Comment by Youda008** [comment]
Ok, i added a button.
You can try it here before the release [DoomRunner-1.8.2(preview)-Windows-64bit-static.zip](https://github.com/Youda008/DoomRunner/files/13786944/DoomRunner-1.8.2.preview.-Windows-64bit-static.zip)

**Comment by proydoha** [comment]
Seems to be working as expected! Thank you!

**Comment by Youda008** [comment]
done and released
