### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by axredneck** [Youda008/DoomRunner#123]
I tried to add ENABLE_VKBASALT=1 and __GL_SHOW_GRAPHICS_OSD=1 but they do nothing.
Arch Linux, DoomRunner 1.8.0.

**Comment by Youda008** [comment]
Hm, i was testing it with an application that prints me all the environment variables it uses and it was there. What engine are you trying to run?

**Comment by axredneck** [comment]
I use GZDoom.
Edit: by environment variables i mean "Environment" tab.

**Comment by Youda008** [comment]
Do you have a compiler?

**Comment by Setilla** [comment]
Void Linux here. Both variables work; I take it you don't actually add the "=". (Might sound dumb but we've all been there)

**Comment by axredneck** [comment]
Looks like ENABLE_VKBASALT works after all but other variables don't, so probably i'm doing something wrong.

**Comment by Youda008** [comment]
And does it work when you run this from terminal?
```
__GL_SHOW_GRAPHICS_OSD=1 gzdoom
```

**Comment by Youda008** [comment]
@axredneck Can i close this issue? I tried setting `__GL_SHOW_GRAPHICS_OSD=1` for gzdoom via command line and it does nothing. It seems GZDoom simply ignores this variable.

**Comment by axredneck** [comment]
Sorry for silence, i was on vacation. Now i'm at home again, i'll try a bit later, but yes, it's probably me doing something wrong.
`__GL_SHOW_GRAPHICS_OSD` is Nvidia-specific variable btw.

**Comment by axredneck** [comment]
Everything works now. Closing.
