### ISSUE TITLE
Doom source port config file being ignored/overwritten

### ISSUE THREAD

**Issue by buvk** [Youda008/DoomRunner#125]
I am using DoomRunner 1.8.0 and the latest version of Crispy Doom.

My final launch command looks like this:

"./crispy-doom.exe" -config "crispy-doom.cfg" -iwad "../IWAD/DOOM.WAD"

If I execute the above via command prompt, Crispy Doom launches and uses the config file as expected.

If I execute the above via DoomRunner, my config file is overwritten, and all my settings are lost.  A new folder called "Crispy Doom" is created within my "D:\Games\Doom\Crispy Doom" folder.

I do not have this issue with DoomRunner 1.7.3.

**Comment by Youda008** [comment]
Overwritten? 😱 But the launcher doesn't write to the config files.

**Comment by buvk** [comment]
> Can i please see your `options.json` file?

[options.zip](https://github.com/Youda008/DoomRunner/files/12242125/options.zip)

**Comment by Youda008** [comment]
Hmm, this is a peculiar problem, i don't understand where it's comming from. All the paths i'm seding to the engine are correct.
And it's only a Crispy Doom doing this, not any of the other engines.

**Comment by Youda008** [comment]
So apparently, Crispy Doom cannot handle being started from another directory using relative executable path (no idea what's going on there that this is a problem).
Luckily, there seems to be a simple workaround. Can you please try this modified version? [DoomRunner-Crispy-workaround.zip](https://github.com/Youda008/DoomRunner/files/12242997/DoomRunner-Crispy-workaround.zip)

**Comment by buvk** [comment]
This version fixes the issue.

**Comment by Youda008** [comment]
Awesome, i will release this fix officially soon together with some others.

**Comment by Youda008** [comment]
fixed
