### ISSUE TITLE
[BUG] the alternative path point ALWAY on target directory.

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#129]
Even if I navigate to an alternate path, 
I do NOT check "preset name as target directory".
the browse save dir and screenshot dir , always redirects to the engine folder.
you have to copy the folder address as text for doom to see the savegames.
thanks !

**Comment by Youda008** [comment]
Thanks for reporting, i will take a look.

**Comment by Youda008** [comment]
Hi, can you try if it works with this version?
[DoomRunner-1.8.2(preview)-Windows-64bit-static.zip](https://github.com/Youda008/DoomRunner/files/13786940/DoomRunner-1.8.2.preview.-Windows-64bit-static.zip)

**Comment by Caiuzx** [comment]
yes it is perfect. Change name also to the preset always goes in the folder that the player gives to the engine. 
Only thing , which , comes from the engine , like gzdoom , that you use often , is that the ini "gzdoom.ini" always goes in Documents/my games/gzdoom 
It would be nice to get it into the Doomrunner folder :D or "default" folder 
*good holidays and happy start 2024*

**Comment by Youda008** [comment]
I'm not sure i understand, but if you want to configure DoomRunner to see files of new GZDoom,
go to Menu -> Initial Setup, double-click on your GZDoom, and change the Config dir and Data dir like this
![obrazek](https://github.com/Youda008/DoomRunner/assets/20306543/b3c4361d-311c-4751-afbb-a72157b780b6)

**Comment by Caiuzx** [comment]
yes ! ok! :)

**Comment by Youda008** [comment]
fixed and released
