### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by DanTheDood** [Youda008/DoomRunner#131]
It's either im dumb or there is an app I need to install. It does not say in desc. It just says extract but there is no exe or setup or anything... I checked the install folder but there is just a desktop file which I searched up and is only limited to ubuntu (I am windows) and an XML file and also the different icons. Do I need to compile it into an exe or smth?

**Comment by DanTheDood** [comment]
Update: it says I need scoop or smth

**Comment by DanTheDood** [comment]
DOWNLOADED! thanks

**Comment by Youda008** [comment]
I like issues that solve themselfs 😄 

For others: You need to go to the release page
![obrazek](https://github.com/Youda008/DoomRunner/assets/20306543/ff77f8a2-eb95-4af4-ad12-f71ff3491b0d)
and download the `Windows-32bit` or `Windows-64bit` zip, inside which is the exe file.
