### ISSUE TITLE
Doom Runner doesn't find info files that are .TXT and not .txt

### ISSUE THREAD

**Issue by thecnoNSMB** [Youda008/DoomRunner#132]
As in the title. This might be exclusive to Linux, since it's very particular about case sensitivity.

Reproduction steps:
1. Create or download a WAD and corresponding TXT file (or perhaps you already have some!), named `NAME.WAD` and `NAME.TXT` or similar, as is the classic convention
2. Double click `NAME.WAD` in Doom Runner
3. Doom Runner fails to find `NAME.txt`, even though `NAME.TXT` is right there

In my case, I ran into this issue trying to play Doomkid's [Vanilla Doom Wad Pack](https://www.doomworld.com/forum/topic/114671/).

**Comment by Youda008** [comment]
Ooops, sorry about that.

**Comment by Youda008** [comment]
Fixed. Release will hopefully be soon.

**Comment by thecnoNSMB** [comment]
Thanks! Doom Runner is easily the best launcher which currently supports Linux (though it's basically only competing with ZDL for some reason), and so I'd like to thank you for your work on it.
