### ISSUE TITLE
GZDoom ini default store path changed after 4.9.0

### ISSUE THREAD

**Issue by ibin7777** [Youda008/DoomRunner#135]
Just noticed this in gzdoom update log, not sure if this affects doomrunner in any way, thought you might need to know:

Important note to Windows users:
GZDoom 4.9.0 changes where gzdoom.ini is stored. Unlike older versions this one will always prefer the system's user folder and place the INI in Documents/My Games/GZDoom if no INI is found. This was done to bring handling in line with current guidelines and to make it easier for commecial games that often get installed into a folder without write access. If you still want to store the INI in your game folder you have to create an empty file called GZDoom_portable.ini there before launching. If you still have an old INI in your folder, GZDoom will ask what to do with it, you can either move it to the user folder or convert to a portable install.

**Comment by Youda008** [comment]
Yes, i adapted DoomRunner to this in 1.8.0. Have you found a bug?

**Comment by Youda008** [comment]
Though if you already used GZDoom with DoomRunner before, and you just updated already existing GZDoom directory, you will need to manually update the config/data dirs in DoomRunner Initial Setup. Automatic detection only works for newly added entries.

**Comment by ibin7777** [comment]
> Yes, i adapted DoomRunner to this in 1.8.0. Have you found a bug?

No bugs, just wanted to ask if it is necessary to manually create the GZDoom_portable.ini file if I want to keep Doomrunner portable?

**Comment by Youda008** [comment]
DoomRunner's portability depends on where it's installed - Program Files or somewhere else.
`GZDoom_portable.ini` determines whether _GZDoom_ is portable. You have to ask GZDoom devs for details, but when i tested it, it always asked me if i want to make it portable or not, after updating from older to 4.9 or newer.
