### ISSUE TITLE
Cannot re-enter initial setup after first time (linux)

### ISSUE THREAD

**Issue by Chloroxite** [Youda008/DoomRunner#136]
This seems like a pretty big oversight.
I closed the program after the first launch because I was just seeing if it worked, so I could relaunch it in another workspace, only to find that after this initial launch, there seemingly absolutely no way to re-enter the initial setup, and I couldn't track down the configuration file to delete/edit it either, so now the launcher is basically entirely useless to me. Any quick solution would be appreciated, but this should probably be changed.

**Comment by yum13241** [comment]
Menu > Initial Setup.

**Comment by Youda008** [comment]
![image](https://github.com/Youda008/DoomRunner/assets/20306543/36acfe3d-2650-40f1-99c5-3d5a96a173f1)

Sorry, it's probably not very visible, but i don't have any idea for a better alternative.

**Comment by Chloroxite** [comment]
Oh shit I don't think the menu button appears if you're using I3 as your window manager on linux. I might need to look at how to make it show.

**Comment by Youda008** [comment]
Linux window managers 😩😫😭 
Can you try to select different application style in the Initial Setup?
If you don't want to lose all data by starting from scratch, then open `options.json`, find `"app_style"` and enter `"Fusion"`.

**Comment by Chloroxite** [comment]
I reinstalled to check last night and realized the button was indeed there. There's no problem, I am shrimply stupid. Have a nice day!
