### ISSUE TITLE
Configuration file not working for MacOS

### ISSUE THREAD

**Issue by Young-Angelo** [Youda008/DoomRunner#141]

**Comment by Young-Angelo** [comment]
The Select config file option does not seem to be working in MacOS

**Comment by Youda008** [comment]
Can you be more specific please? Is the combo-box empty? Or does it ignore your choice?
I don't have a Mac computer, so i cannot try and reproduce this myself. That why Mac is not officially supported.
But if you tell me enough details, maybe i can make it work.

**Comment by jakestanley** [comment]
I'll take a look at this one. @Young-Angelo if you could provide a screenshot that'd be grand

**Comment by jakestanley** [comment]
You may not have selected a config directory for your selected engine. If you set up your engine again, you need to specify where your configs are stored:

<img width="1085" alt="Screenshot 2024-01-11 at 09 46 22" src="https://github.com/Youda008/DoomRunner/assets/2962500/e2994d07-0391-4b0a-8c8d-ad089abb27e7">
<img width="793" alt="Screenshot 2024-01-11 at 09 46 33" src="https://github.com/Youda008/DoomRunner/assets/2962500/708952b0-b13b-4f4f-8dbe-2e9a31ca4c01">

**Comment by jakestanley** [comment]
In Menu -> Initial setup

**Comment by jakestanley** [comment]
@Young-Angelo did this resolve your issue?

**Comment by Young-Angelo** [comment]
> @Young-Angelo did this resolve your issue?

Yes!!, sorry for creating a issue for an user error 😅

**Comment by Young-Angelo** [comment]
> Can you be more specific please? Is the combo-box empty? Or does it ignore your choice? I don't have a Mac computer, so i cannot try and reproduce this myself. That's why Mac is not officially supported. But if you tell me enough details, maybe i can make it work.

It was an User error 😅, Even though MacOS isn't officially supported, it runs great on the platform. Thank you for making this cross platform. Most doom stuff are Windows/Linux only and im glad some love is shown to Mac.

**Comment by Youda008** [comment]
When you're already trying Doom Runner on Mac, can you please try if it works when you

- right-click on any mod file and select "Open file location",
- click on that folder button next to the engine drop-down list

**Comment by Young-Angelo** [comment]
> When you're already trying Doom Runner on Mac, can you please try if it works when you
> 
> * right-click on any mod file and select "Open file location",
> * click on that folder button next to the engine drop-down list

<img width="862" alt="image" src="https://github.com/Youda008/DoomRunner/assets/16363526/9a6e02ea-7d1a-43db-a969-bacbe9c176f9">

The file folder seems to have opened but it says error

**Comment by Young-Angelo** [comment]
Adding folders as mod doesn't seem to work

**Comment by jakestanley** [comment]
@Youda008 is this feature supported on Windows?

**Comment by jakestanley** [comment]
Just checked on my recent build and it appears to work. It might be that the app has been denied Finder permissions on @Young-Angelo 's system

**Comment by Youda008** [comment]
Today i made a commit that probably fixes it.

**Comment by Young-Angelo** [comment]
> Just checked on my recent build and it appears to work. It might be that the app has been denied Finder permissions on @Young-Angelo 's system

the file opens but i also get an error false positive, how do i fix that?

**Comment by Youda008** [comment]
Can you please try with the newest release?

**Comment by Young-Angelo** [comment]
Says the application is damaged and cannot be opened.
<img width="464" alt="image" src="https://github.com/Youda008/DoomRunner/assets/16363526/9845069f-3bcf-4b23-9b05-c7157d86de77">

**Comment by Young-Angelo** [comment]
But building from source seems to fix the bugs I had earlier with file not opening correctly.
