### ISSUE TITLE
[Bug] "Cannot read version value" error

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#142]
With latest release, I get an errors.txt in my DoomRunner dir, stating the following:

> [2024-01-16T15:05:51] [FAILURE] ExeReader: Cannot read version value, VerQueryValue("\StringFileInfo\040904e4\FileDescription") returned 0x2a429fd5abc,0

This already happened with dev builds and I hoped it would disappear with the final v1.8.2 release, but it's still a thing.

Used build: Static, Win x64

**Comment by Youda008** [comment]
Damn, i forgot to log what file name it is.
Can you try to run DoomRunner.exe from command line if it doesn't print any more info?

Anyway this is not a serious problem, it just says that one of the exe files that you added as Doom engine does not have a valid version info inside itself. But we don't know which one.

**Comment by Youda008** [comment]
I just didn't think that this particular case of exe version info is possible, i thought it is a sign of the version info being corrupted, so i rather included a silent error report. I can remove it of course. But i don't think its worth making a new release just for this one problem.

**Comment by NightFright2k19** [comment]
I'd say remove the warning and it'll be in the next official release. For me it's OK, I can build the launcher via tools if I need this change right away, then.

**Comment by Youda008** [comment]
I commited a change that will log the problematic file name to stdout,
so if you run DoomRunner.exe from command line, you should be able to see which file doesn't have what.
But you'll probably have to delete `file_info_cache.json` before that.
