### ISSUE TITLE
[suggestion] Keyboard shortcuts and default active panel

### ISSUE THREAD

**Issue by mstempell** [Youda008/DoomRunner#144]
Would be great if the "presets" list-box had the default focus (so with the cursor active in it),
and if the "Launch!" button had a shortcut (like F10 maybe?).

Also being able to select the active list-box with a shortcut would be great (maybe F1 to F6, according to their numbers?).
And even the action buttons could have shortcuts (move up and move down are already handled by the default ctrl+up and ctrl+down, so just for the other buttons).

**Comment by mstempell** [comment]
Browsing the closed issues, I saw that some buttons had shortcuts (new, delete).
Maybe having a button tooltip mentioning those would be interesting.

**Comment by mstempell** [comment]
Actually my F1 to F6 idea may interfere with the OS usage... (like F2 on windows, which renames things).
So maybe rather ctrl+1 to 6?

**Comment by Youda008** [comment]
That can probably be done.

**Comment by Youda008** [comment]
Ok, i forgot my main target audience are DOS enthusiasts who hate to use mouse 😂 
It will be done shortly.

**Comment by Youda008** [comment]
It has landed in the master branch, it will be part of 1.8.3 release.
