### ISSUE TITLE
[Bug] "Path of the selected mod is empty" with latest dev build

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#147]
When using the latest dev build, I get this message when launching my mods:
_"Path of the selected mod is empty. Please update your mod list."_

The command line adds three empty arguments/quotes at the end, like this (when trying to launch unmodded Heretic):
_"./crispy-heretic.exe" -iwad "../../iwad/heretic.wad" -file "" "" ""_

With a PWAD loaded:
_"./crispy-heretic.exe" -iwad "../../iwad/heretic.wad" -file "../../pwad/heretic/puss28_qtr.wad" "" "" ""_

**Comment by Youda008** [comment]
Thanks for reporting. Should be fixed now.
