### ISSUE TITLE
[Feature] Proper loading of deh/hhe patches

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#149]
When selecting a DEHACKED lump for Doom or Heretic (.deh/.hhe) as a mod, DoomRunner would add it to the command line via -file parameter. This wouldn't work. 

If it's doable, it'd be great if the launcher automatically picked the -deh parameter instead for such file endings.

**Comment by NightFright2k19** [comment]
Not from the top of my head. HHE is kinda exotic, but Chocolate, Crispy and compatible support it, both as external file to load and an internal lump, renamed to HEHACKED.

**Comment by Youda008** [comment]
Commited to master.

**Comment by NightFright2k19** [comment]
I think we can consider this one closed. Thanks for implementing! ^^
