### ISSUE TITLE
Next step : load a savegame with the preset ? you can ?

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#15]
can you enter a window to see the savegame for that preset? and then load them?

**Comment by Youda008** [comment]
That would be kind of difficult. Actually a lot difficult, as i would have to read and parse the .zds files and find out which ones were saved with the exact same mods.

**Comment by DanilaSpevak** [comment]
Just a quick idea - perhaps it would be enough to allow using different save folders for different presets? 

For example, I've got presets for Brutal Doom and presets for Guncaster. In each case I can enable or disable different minor mods, and major PWADs can be updated over time as well, so parsing mod list from zds woudn't help.
But if save files are separated by folders, I can make reasonable decision - whether I shoud update current preset of make a new one.

In that case, to see savegames for presets there are two options:
a) simply show save files in a list, or
b) just run the game, and in "load game" menu you'll see a list of saves for your preset.

I don't quite see what problem Caiuzx was trying to solve, but I think the second option would be enough as adding step 7 to  "Files" page looks like too much.

**Comment by Caiuzx** [comment]
interesting - you could have doomrunner copy the files to a folder so that you have bat and mod in the same folder.
as happens to another launcher;)

**Comment by Youda008** [comment]
> Just a quick idea - perhaps it would be enough to allow using different save folders for different presets?

You can already do that. Just go to "Initial Setup" and choose "Save to preset".

**Comment by Youda008** [comment]
I will close this for now, because you can already achieve what you want by selecting this option
![assign-savegame-to-preset](https://user-images.githubusercontent.com/20306543/140488912-9f69b914-5367-4121-af24-70e17bfbcde4.png)
If this is not enough for you and you have a better idea, reopen the issue and write a comment.
