### ISSUE TITLE
pls help with multiplayer 

### ISSUE THREAD

**Issue by horay133** [Youda008/DoomRunner#159]
I don't know how to make the multiplayer work i want to make a server using GZDOOM

**Comment by horay133** [comment]
and i dont get what im doing wrong

**Comment by horay133** [comment]
give my a sec i will get screenshots

**Comment by horay133** [comment]
![image](https://github.com/Youda008/DoomRunner/assets/57258910/a8154bb2-9408-4e39-bf91-b432dcecd43a)
the host

**Comment by horay133** [comment]
i tried using the ip of my desktop but it got nowhere

**Comment by horay133** [comment]
it trying to run good old fashioned doom 2 for testing the multiplayer

**Comment by Youda008** [comment]
You have to enter the IP address or host name of the computer with Server role.
If it doesn't connect, then it's probably blocked by a firewall or Windows network profile.

**Comment by horay133** [comment]
how do i unblock it

**Comment by horay133** [comment]
maybe it dos not work because my pc and laptop in the same ip

**Comment by Youda008** [comment]
If you're using Windows firewall try to go to Network settings, click on your active connected network
![image](https://github.com/Youda008/DoomRunner/assets/20306543/5437b3f1-0b68-4c43-b60b-5747fef9b976)
and switch to private
![image](https://github.com/Youda008/DoomRunner/assets/20306543/fb79d577-5e6b-4a31-902c-763c8e7a2cb6)

Also go to the Windows Firewall
![image](https://github.com/Youda008/DoomRunner/assets/20306543/71ae4c6c-95e9-4c77-9e09-cf9d443387ab)
select "Allow an app through firewall"
![image](https://github.com/Youda008/DoomRunner/assets/20306543/cea93fda-6812-4326-80e1-8d96e87e2232)
and add GZDoom.

If you're using some third party firewall or antivirus, you have to somehow allow GZDoom to communicate over UDP port shown in the Doom Runner (5029), on both computers.
