### ISSUE TITLE
ui for screenshot and save.

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#16]
ui for screenshot in select engine ?

**Comment by Youda008** [comment]
What do you mean? You want to specify a directory for screenshots for each engine?

**Comment by Caiuzx** [comment]
> 
> 
> What do you mean? You want to specify a directory for screenshots for each engine?

Yes, if you can, for each screenshot and save , you can make a folder ? 
Whenever you play a map, saves and screenshots always end up in the same folder engine. It would be nice to have them divided, to reload the old saves or to see that I played that mod or map.

don't you have an excel or google sheet for the maps and mods you play ???

**Comment by Youda008** [comment]
Done. Will be released soon.
