### ISSUE TITLE
Add Music and Textures lists

### ISSUE THREAD

**Issue by summer1090** [Youda008/DoomRunner#161]
Option to add Music and Textures list the same way as you did with Maps, so users will point to separete directories with Music and Textures, as usually all of that needs to be load before mods.

**Comment by thecnoNSMB** [comment]
You can easily achieve this yourself by changing the mod load order and adding a separator. Mods load top to bottom.

**Comment by thecnoNSMB** [comment]
> You can easily achieve this yourself by changing the mod load order and adding a separator. Mods load top to bottom.

Whoops, might have misunderstood you there. If you're instead asking about multiple load directories, the way I personally handle it is to point Doom Runner to the parent directory containing the folder with my gameplay mods and the folder with my texture mods.

**Comment by Youda008** [comment]
I'm sorry, but I personally don't think this is a good idea.
1. Sometimes the music or textures need to be applied after the gameplay mods and the launcher would have hard times recognizing the correct order.
2. Apart from textures and music there is potentially infinite number of other categories of additional files to load, and the UI would get cluttered fast with adding new lists.

Having a single list for all "all additional files except maps" with the possibility to add separators between categories allows you to do everything you need without the UI becoming too big and complicated.

**Comment by summer1090** [comment]
ok, thanks all, throw away the idea,
however showing relative path of loaded wad could be usefull, as I also put Textue, Music, Megawads, Maps under Mods directory
