### ISSUE TITLE
DSDA-Doom doesn't recognize -netmode flag

### ISSUE THREAD

**Issue by thecnoNSMB** [Youda008/DoomRunner#162]
As in title; this makes the multiplayer section under "More options" effectively unusable. I am using DoomRunner 1.8.2 and have dsda-doom set up in the launcher as part of the PrBoom family (though I can't check this, because there's no way to edit a source port entry once you've added it!)

**Comment by thecnoNSMB** [comment]
It also doesn't recognize `-join` if I instead select to launch as client. I suspect there's a lot more incompatibilities hiding around here.

**Comment by thecnoNSMB** [comment]
> > though I can't check this, because there's no way to edit a source port entry once you've added it!)
> 
> Menu > Initial Setup

~~Yeah, that lets you *delete* or *add* source port entries, but not edit them.~~ Apparently you _can_ edit them by double clicking the entry! I can confirm DSDA-Doom is set up for me as being in the PRBoom family.

**Comment by Youda008** [comment]
@thecnoNSMB I tried searching the DSDA Doom manual/wiki/documentation or any other internet source about it, and i found nothing about multiplayer. It seems DSDA Doom doesn't support multiplayer at all. So there is no way to fix this.

**Comment by thecnoNSMB** [comment]
That would explain it, lol.
