### ISSUE TITLE
(Linux newbie) Trying to play doom via doomrunner and it keeps giving me this error (See picture)

### ISSUE THREAD

**Issue by bugerkin** [Youda008/DoomRunner#166]
Trying to play doom via doomrunner and gzdoom and it keeps giving me this message when ever I hit launch.
![doom](https://github.com/Youda008/DoomRunner/assets/87587767/b8b07b71-6f0d-4d5d-8cb4-9b010f633422)

**Comment by summer1090** [comment]
deb is package file with engine, you need to install the package first and only then select the gzdoom

**Comment by Youda008** [comment]
As summer1090 said. The .deb file is an installation package, something like the .msi on Windows.
It's not a program you can immediatelly run. You have to install it first
https://askubuntu.com/questions/40779/how-do-i-install-a-deb-file-via-the-command-line
then find the installed executable (usually in `/usr/bin`, `/usr/local/bin`, ..., you can use `which` command to find where it is) and add that one into Doom Runner.

**Comment by bugerkin** [comment]
![hshsh](https://github.com/Youda008/DoomRunner/assets/87587767/d8d11570-d9fc-4ad3-aa06-4e79866d2877)
So I did what you told me to do in the terminal but for some reason I can't change the executable. (I'm clicking the folder icon and trying to select the executable file but It just doesn't work)

Also I thought I could fix this problem via reinstalling through linux mint's software manger but now I can't change the theme, Add both the Doom 1 & 2 Iwads and add any map packs.

**Comment by Youda008** [comment]
You need to click Menu -> Initial Setup and edit it there.

**Comment by bugerkin** [comment]
Sorry for the late response but everything works now after helping me.

Thanks!
