### ISSUE TITLE
Map pack section scrolls to the center if there's a long named file

### ISSUE THREAD

**Issue by randomname42** [Youda008/DoomRunner#168]
This is what happens any time I click a preset:

![Screenshot_DoomRunner map panel](https://github.com/Youda008/DoomRunner/assets/31464072/25588383-2e34-4598-906a-b2545cba80d1)

Clicking a preset centers the scrollbar on the maps section, even if it was previously scrolled to the left so that the beginning of filenames  were visible. You have to move the scrollbar to the left every time you click a preset if a filename is long enough to cause the horizontal scrollbar to appear.

I'm using flatpak on Steam Deck but I doubt that's a factor.

**Comment by Youda008** [comment]
Ok, this is a very counter-intuitive default behaviour of Qt, but luckily i found a workaround.

**Comment by Youda008** [comment]
Should be fixed now.
