### ISSUE TITLE
Allow loading folders for mods

### ISSUE THREAD

**Issue by nashmuhandes** [Youda008/DoomRunner#17]
GZDoom lets you load folders directly with the -file parameter.

(Just for your information, ZDoom Executor supports loading folders)

**Comment by Youda008** [comment]
Thanks. I will do it, but not sure when. The will to work on hobby programming projects nowdays is very low, as i have to stay at home programming all day for living, and then when i finish work, i don't even standup from the computer, so i kinda don't want to just switch from one programming task to another and continue. I think i will continue on this launcher when the quarantine ends.

**Comment by nashmuhandes** [comment]
> Thanks. I will do it, but not sure when. The will to work on hobby programming projects nowdays is very low, as i have to stay at home programming all day for living, and then when i finish work, i don't even standup from the computer, so i kinda don't want to just switch from one programming task to another and continue. I think i will continue on this launcher when the quarantine ends.

Understood, please rest and stay safe! Thank you for making this launcher for others to enjoy.

**Comment by Youda008** [comment]
And how do you image it should work in the UI? That you can add an entry into the mod list which is a directory? Or that you select directory and it adds all the files inside?

**Comment by nashmuhandes** [comment]
[Imgur](https://imgur.com/arloFg2)

UI-wise, something like this maybe. Separate buttons to load either a directory or a file.

Internally, how it would work is it simply passes the full path string to the -file parameter, eg:

``-file "C:\Doom\Maps\AwesomeMap.wad" "C:\Doom\My Weapon Mod"``

**Comment by DanilaSpevak** [comment]
If you use Unocode symbols for buttons, take a look at U+1F4C1 and U+1F5C0 symbols. Maybe one of them will do?

**Comment by Youda008** [comment]
Done. Will be part of next release. In the meantime you can drag&drop a directory from file manager window. This has worked the whole time, but i didn't realize it.
