### ISSUE TITLE
v1.8.2 Intel Mac application quits unexpectedly when I try to open it

### ISSUE THREAD

**Issue by AaronWizard** [Youda008/DoomRunner#172]
OS: macOS 14.5
Hardware: 2018 Mac mini, Intel Core i7

I downloaded and opened the "DoomRunner-1.8.2-MacOS-x86-64.dmg.zip" release file since I have an Intel Mac. When I try to open DoomRunner I get the error dialogue "DoomRunner quit unexpectedly". This dialogue has a "Report" option, which opens a Problem Report dialogue.

The problem report contains the following error near the top:

    Termination Reason:    Namespace DYLD, Code 1 Library missing
    Library not loaded: /usr/local/opt/qt/lib/QtWidgets.framework/Versions/A/QtWidgets
    Referenced from: <A86621D0-497B-3FB5-9F9C-2554681FB0A5> /Users/USER/Downloads/DoomRunner.app/Contents/MacOS/DoomRunner
    Reason: tried: '/usr/local/opt/qt/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/qt/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/usr/local/opt/qt/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file)
    (terminated at launch; ignore backtrace)

I've attached the full text of the problem report:
[problem_report.txt](https://github.com/user-attachments/files/15983758/problem_report.txt)

**Comment by AaronWizard** [comment]
The DoomRunner application works after I install Qt with Homebrew.

**Comment by Youda008** [comment]
perfect 👍
