### ISSUE TITLE
Please make the "add mod file" dialog remember the last folder used/not get lost when saving files in the web browser.

### ISSUE THREAD

**Issue by randomname42** [Youda008/DoomRunner#173]
I'm on Steam Deck flatpak.

Whenever I save a file in Firefox, the folder where that file was saved to is the folder Doom Runner will open to when hitting "add mod file".

This happens every time a file is saved in Firefox, and makes no difference if Doom Runner is open at the time or not. Even when Doom Runner is open and the mod folder had previously been browsed to without closing Doom Runner, this still happens.

For example:
1. open Doom Runner, and add a mod. This will remember the folder for the next time you open it.
2. except, now go save an image or something in Firefox. Even if you had Doom Runner open and had added a mod, hitting "add mod folder" will now open to the folder that Firefox saved to. Doom Runner forgets the folder you had browsed to every time in that situation.

I don't know why this happens, as browsing to a mod folder for Doom Runner and adding a mod does not make Firefox try to save to the folder for Doom Runner mods.

It would be very nice not to have to browse to the mod folder again any time Doom Runner is opened and you want to add a mod (because most often a file will have been saved in Firefox between the last time I used Doom Runner).

**Comment by Youda008** [comment]
That's not DoomRunner doing it, that the operating system who controls the file dialogs.
But maybe there is some way to override that.

**Comment by Youda008** [comment]
@randomname42 Interesting, i already have a code that explicitly tells the file dialog to open at the path that you enter here
![obrazek](https://github.com/user-attachments/assets/87d912c2-b801-4d8f-bbf9-67c4d03500c9)
and it works fine in Windows and in Kubuntu.
Which means it's a bug either in Qt or in the Steam Deck OS, and i'm affraid i cannot do anything about those.
