### ISSUE TITLE
Map pack selection list doesn't account for folder structure

### ISSUE THREAD

**Issue by PyronoidDev** [Youda008/DoomRunner#19]
Selecting your maps directory and checking 'Search also in subdirectories' correctly populates the list of maps available in a directory and its sub-directories, but when loading a map pack with the maps list, the directory structure is not correctly copied into the launch command.

For example, if the map is in '../Maps/Single Player/Map Pack/map pack.wad', when selected in the list, it will populate as '../Maps/map pack.wad', which will then not load.

Please see attached screenshot for an example.

![doomrunner error](https://user-images.githubusercontent.com/39367006/76941219-8a9b5a00-68f3-11ea-9a61-ec622483bd5f.png)

**Comment by Youda008** [comment]
Hi. Please try it with the newest version. I think this bug was already fixed some time ago.

**Comment by Caiuzx** [comment]
> 
> 
> Selecting your maps directory and checking 'Search also in subdirectories' correctly populates the list of maps available in a directory and its sub-directories, but when loading a map pack with the maps list, the directory structure is not correctly copied into the launch command.
> 
> For example, if the map is in '../Maps/Single Player/Map Pack/map pack.wad', when selected in the list, it will populate as '../Maps/map pack.wad', which will then not load.
> 
> Please see attached screenshot for an example.
> 
> ![doomrunner error](https://user-images.githubusercontent.com/39367006/76941219-8a9b5a00-68f3-11ea-9a61-ec622483bd5f.png)

it's fix on 1.2

**Comment by PyronoidDev** [comment]
Oh goodness, I thought I had the latest version but I must have messed up updating my installation!

Apologies for the erroneous issue, I can see now that the map selection works just fine.

Thanks for all your great work!
