### ISSUE TITLE
Close on Launch

### ISSUE THREAD

**Issue by drakuleah** [Youda008/DoomRunner#190]
Is there an option to close DoomRunner on launch?
I mean, closing DoomRunner on a successfully launch session?

Thanks!

**Comment by Youda008** [comment]
Menu -> Initial Setup
![obrazek](https://github.com/user-attachments/assets/0ea10d6e-934f-45f3-8312-d0a2ab0a2bcf)

**Comment by drakuleah** [comment]
Great!
Sorry about my distraction.

Thanks a lot!!!
