### ISSUE TITLE
macOS (x86): Engine selection not working

### ISSUE THREAD

**Issue by andynameistaken** [Youda008/DoomRunner#191]
Clicking file chooser icon does nothing.

**Comment by Youda008** [comment]
I need little bit more information. I have no idea which button or UI element you have in mind.

**Comment by andynameistaken** [comment]
I'm sorry it was my mistake, I overlooked process of selecting folders on first run. Although I found another bug: program crashes when creating preset. I will check out if such submission exists and file it if not. Also if you want I can test out macOS source builds with every update as I've seen next release doesn't have macOS build.
