### ISSUE TITLE
Support Woof source port

### ISSUE THREAD

**Issue by amethystgosling163** [Youda008/DoomRunner#192]
[project page](https://github.com/fabiangreffrath/woof)

It's available as an [AppImage](https://appimage.org/) for Linux and as a portable program archive for Windows.

**Comment by Youda008** [comment]
What exactly is not working for Woof? There is a basic support in the launcher already.

**Comment by amethystgosling163** [comment]
> What exactly is not working for Woof? There is a basic support in the launcher already.

Sorry for making the issue! I didn't realize that Woof support was already baked in 🫠. Closing the issue now.
