### ISSUE TITLE
Show waiting cursor while app opens on Linux

### ISSUE THREAD

**Issue by amethystgosling163** [Youda008/DoomRunner#193]
Just need to add `StartupNotify=true` line to the desktop entry file of the application.

**Comment by Youda008** [comment]
like this https://github.com/Youda008/DoomRunner/pull/195 ?

**Comment by amethystgosling163** [comment]
Yeah

**Comment by amethystgosling163** [comment]
Yeah

**Comment by amethystgosling163** [comment]
Yeah. It's fine, I think.

**Comment by amethystgosling163** [comment]
On second thought, I think the 'T' in "True" needs to be lowercase.
