### ISSUE TITLE
[Request] Subdir search/filtering

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#2]
Search all subdirs for wads, mods or maps. With a folder structure like e.g. wads\pwad\doom1, wads\pwad\doom2, wads\pwad\heretic etc to keep map packs for all different games apart, you can currently only select one of these, but not all (by using wads\pwad as root dir). Even better would be to allow game-specific map/mods directories (so that you only see those mods working with a specific game, e.g. only for Doom, Doom II, Heretic, Hexen etc).

**Comment by Youda008** [comment]
Hi. With subdirs that can definitely be done, it should be easy. I'm not sure about the game specific wad dirs, as that would double the size of the window and required settings and ruin the nice simplicity of the main tab.

**Comment by Caiuzx** [comment]
also my problem, else it's complete and simple launcher ! make a web site ! or forum thrend on doomworld.com 💃

**Comment by Youda008** [comment]
I'm no web developer, and i have nowhere to host it. I made a thread on zdoom.org, but it didn't get much attention.

**Comment by Caiuzx** [comment]
this is a template
https://www.doomworld.com/forum/topic/87120-rocket-launcher-20-cross-platform-doom-front-end/?tab=comments#comment-1584747
give screenshot and post on doom general :)

**Comment by Youda008** [comment]
This feature is now alive in release 1.0. Thank you.
