### ISSUE TITLE
[Suggestion] Allow advanced launch options without specifying a map

### ISSUE THREAD

**Issue by axredneck** [Youda008/DoomRunner#20]
E.g. what if i want to run a mod with some options but don't want to load any particular map but go into main menu and intro instead?

**Comment by Youda008** [comment]
What advanced options exactly?

**Comment by axredneck** [comment]
Those in "Gameplay options" and "Compatibility options" buttons

**Comment by Youda008** [comment]
Well that will not work. In ZDoom those options only apply when you launch a map. If you launch into game menu, it expects you to set those in the menu.

**Comment by axredneck** [comment]
Thank you.
