### ISSUE TITLE
Controls per Preset

### ISSUE THREAD

**Issue by Eragon615** [Youda008/DoomRunner#200]
I'm not sure if this is a feature request or a bug. Some of the mods I play have _questionable_ choices on key placement, so I have keymaps that are odd for any other packs and presets. I would think I should be able to store them, either in the named configs (section 5 in the GUI) or in the Preset (section 1 in the GUI) but that doesn't seem to be the case. It seems like it always uses whatever is in gzdoom.ini, despite the fact I can see the remapped controls in the named config files. 

If it matters, I'm on Arch Linux, using the Flatpak version of Doom Runner.

**Comment by Youda008** [comment]
I'm not sure i understand.
The game controls (key bindings) are stored in config files (`ini` files in GZDoom). Are you saying you selected a different ini file and it ignored your custom controls?

**Comment by Eragon615** [comment]
Yes, exactly. Guess that makes this a bug report. So I've got one called Testing.ini and the other is the default gzdoom.ini. If I go and change a setting in testing, it seems to update gzdoom.ini as well. And if I delete gzdoom, it wipes my configs even when I've got Testing select.

**Comment by mbugni** [comment]
> If it matters, I'm on Arch Linux, using the Flatpak version of Doom Runner.

It could matter. Can you attach the command line produced by DoomRunner when you use you custom config file?

**Comment by Eragon615** [comment]
```
GZDoom -config "/home/clayton/.var/app/io.github.Youda008.DoomRunner/config/Testing.ini" -iwad "/home/clayton/Games/Doom/Maps/Official Games/DOOM2.WAD" -savedir "/home/clayton/.var/app/io.github.Youda008.DoomRunner/data/Testing" -shotdir "/home/clayton/.var/app/io.github.Youda008.DoomRunner/data/Testing"
```
I don't see it calling out the ini file. Guess I should have checked that.

**Comment by mbugni** [comment]
```
-config "/home/clayton/.var/app/io.github.Youda008.DoomRunner/config/Testing.ini"
```

Can you confirm that the file ~/.var/app/io.github.Youda008.DoomRunner/config/Testing.ini exists and contains the desired configurations?

**Comment by Eragon615** [comment]
It does exist. Opening the file in an editor, I can see that setting are in fact set. The thing I've been doing for testing is simply setting the "reload" action to the 'R' key.

1. So I've deleted both testing, and gzdoom.ini. 
2. I've started a game in the Default Preset, just loading OG Doom. That regenerated a gzdoom.ini file. There's no changes whatsoever. 
3. Then I copied it to Testing.ini (using the Doom Runner GUI, if that matters). 
4. Start a game of OG Doom using the Testing Preset, with the Testing.ini config. 
5. Set "reload" to 'R'.
6. Quit the game. Now when I open Testing.ini in a text editor, it seems it wasn't updated, but gzdoom.ini is. 

Not really sure where to go from here. I can screengrab whatever you need.

**Comment by mbugni** [comment]
@Youda008 I think this is an issue of the Flatpak version, due the command launcher. Let me know if you want to keep this bug or we can close it and open a bug to Flathub.

**Comment by Eragon615** [comment]
A little more info that might be relevant. I did edit permissions with Flatseal to allow Doom Runner access to my home directory. If you think that could be related, I can disable that and move the mods into the flatpak's directory.

**Comment by mbugni** [comment]
For the sake of testing, is better to keep the app in the sandbox, which is a Flatpak goal. I think I already fixed the issue.

**Comment by Youda008** [comment]
> I think I already fixed the issue.
Does it require change in the code?

**Comment by mbugni** [comment]
> Does it require change in the code?

Not from DoomRunner side. I already [opened this PR ](https://github.com/flathub/io.github.Youda008.DoomRunner/pull/9)to fix it.

**Comment by Eragon615** [comment]
You guys are awesome. Thanks for the timely support.

**Comment by mbugni** [comment]
@Eragon615 can you please test [this version](https://github.com/flathub/io.github.Youda008.DoomRunner/pull/9#issuecomment-2558574100) and check if it works as expected?

**Comment by Eragon615** [comment]
Way ahead of you. I've tested a few scenarios now, and it seems to be working as intended.

**Comment by mbugni** [comment]
It will be available soon on Flathub.
