### ISSUE TITLE
Option to automatically close ending splash screens

### ISSUE THREAD

**Issue by msmigiel** [Youda008/DoomRunner#201]
When playing most (if not all) Doom WADs, when you exist the game, there is a little splash screen that you must manually close. I am not sure if this is possible, but please consider adding an option to automatically close this so the end user does not have to. Combining this with the flag to close Doom Runner when Doom launches would make the exiting of the game a little cleaner.

**Comment by Youda008** [comment]
This is an engine-specific feature and should be imho configured inside the engine. In GZDoom it's this option
![obrazek](https://github.com/user-attachments/assets/8bf73625-466f-4301-bc31-90d7e6a3af34)

**Comment by msmigiel** [comment]
Thank you, I wasn't aware this was an in game option. If that's the case, it makes sense to not put it in Doom Runner.
