### ISSUE TITLE
Flatpak Doom Runner: GZDoom won't take keyboard input when trying to save or use the console

### ISSUE THREAD

**Issue by randomname42** [Youda008/DoomRunner#203]
Something about a recent update must have caused this to go wrong, because it was working fine in v1.8.2.

On Steam Deck using the flatpak version of Doom Runner, in GZDoom keyboard input is completely ignored in a couple situations.

1. Launch GZDoom from Doom Runner and open up the console with ~
2. Try to type, nothing happens. Even "enter" does nothing
3. The console can be closed with the keyboard (esc), but that seems to be the only thing that the keyboard can do with the console open. This is using the built in GZDoom.

1. Same thing, but when saving. Try to save a new game.
2. When you try to name it, typing does nothing. Enter does nothing as well, which means there's no way to confirm the save. You can only press esc to cancel.
3. As this prevents manually saving, it's a pretty severe problem. This is also using the built in GZDoom.

I am not seeing this problem with the linux non-flatpak version (1.8.3). I can save in dsda-doom using that version of Doom Runner with no problem. It sees what I'm typing. 

However I cannot get GZDoom to run with the non-flatpak version of Doom Runner to matter what I try, so I can't test whether GZDoom is working correctly with the regular linux version of Doom Runner.

**Comment by Youda008** [comment]
I don't think this is an issue of Doom Runner.
Take a look at this: https://github.com/flathub/org.zdoom.GZDoom/issues/55
Following the final advice, you should enter `key: SteamDeck, value: 0` into the environment variables (last tab of Doom Runner).

**Comment by randomname42** [comment]
That works. Thanks.

The thing I don't understand is why it was working correctly before without that variable. Somehow updating must have triggered it.

**Comment by mbugni** [comment]
> The thing I don't understand is why it was working correctly before without that variable. Somehow updating must have triggered it.

The Flatpak version includes at least 3 components:
- the DoomRunner itself
- the GZDoom engine
- the QT runtime

One or more updates of them introduced the bug for you platform.
As @Youda008  mentioned it seems to be related to the GZDoom engine.
