### ISSUE TITLE
[Suggestion] "No music" checkbox

### ISSUE THREAD

**Issue by axredneck** [Youda008/DoomRunner#21]
Sometimes i want to play with my own music instead of using one provided by wad. Rocket Launcher has such feature.

**Comment by Youda008** [comment]
Thank you for feedback. Yes, someone already suggested this either on the DoomWorld forum or ZDoom forum (don't remember). But as there were many other requests what buttons and checkboxes to add, i decided to postpone all of it to the next version and do it together properly. 1.3 is already finalized, and i'm just waiting for a guy to reply me regarding a Doom64 issue, and then i will release what i currently have. 1.4 with all those options will then be hopefully in summer.

**Comment by Youda008** [comment]
Done. Will be released soon.
