### ISSUE TITLE
Cannot unselect map pack by clicking active map pack

### ISSUE THREAD

**Issue by Qinus** [Youda008/DoomRunner#22]
1.3 won't let me click on the active map pack to deselect it, it's working on the 1.2 build. Clicking on the empty space below the map list works, though.

Using Windows 10 v1903

**Comment by Youda008** [comment]
Hi, use CTRL for deselecting or selecting multiple entries, same as you would when selecting files in Explorer directory window.

**Comment by Qinus** [comment]
Thank you, I wasn't sure if it was intentional or not.
