### ISSUE TITLE
Presets, IWADS, maps can only be activated with mouse

### ISSUE THREAD

**Issue by DanilaSpevak** [Youda008/DoomRunner#23]
In DoomRunner 1.3.2, when you change active preset, IWAD or map pack with keyboard arrows Up/Down, nothing happens. You have to actually click the item with mouse.

**Comment by Youda008** [comment]
Pressing enter will now confirm your choice selected with arrow keys. Is that enough?

**Comment by DanilaSpevak** [comment]
That's one way to do it, but still not perfect for two reasons: a) it still requires you to make one extra action, and b) you still get an inconsistent picture without any indication. 

If you are worried about performance issues when scrolling with pressed arrow, you might add some async timer (0.1 sec is actually enough) which resets when you activate list item. So when you hold an arrow button, the timer keeps resetting, and 0.1 sec after you release it you'll have your preset (or iwad, or map pack) selected. Same with Shift+Arrow in map pack list.

**Comment by Youda008** [comment]
Done. Will be part of next release.
