### ISSUE TITLE
[Suggestion] Context menu and Hotkeys

### ISSUE THREAD

**Issue by DanilaSpevak** [Youda008/DoomRunner#24]
While organizing my preset list, I noticed that I reflexively try to use some keys:
1. Insert - for the new preset/mod
2. Delete - to delete current preset/mod
3. Right mouse button - expecting context menu that duplicates control panels in Presets or Mods list

I think, such keys and menus are quite intuitive and provide smoother user experience than having to use toolbars below all the time.

I might also suggest Ctrl-Shift-Up/Down for move up/down commands

**Comment by Youda008** [comment]
Good idea. Adding to my TODO list.

**Comment by Youda008** [comment]
Done. Will be part of next release.
