### ISSUE TITLE
Can't unselect a mappack once selected

### ISSUE THREAD

**Issue by FirestarJes** [Youda008/DoomRunner#25]
If you have selected a map pack, you can no longer unselect anything in this listbox, meaning you have to select a mappack even if you may not want to.

**Comment by Youda008** [comment]
Hold CTRL and press it again. It behaves the same as file entries in directory window.

**Comment by FirestarJes** [comment]
That works, must have missed that somehow.


man. 16. nov. 2020 16.57 skrev Youda008 <notifications@github.com>:
