### ISSUE TITLE
.deh files added in Mods section affected by capitalization of file extension

### ISSUE THREAD

**Issue by Berzasperd** [Youda008/DoomRunner#27]
While DoomRunner will automatically detect a .deh file added as a mod and generate a final launch command with the appropriate -deh parameter, it will fail and default to the -file parameter if the file extension of the actual .deh is capitalized in any way.  To load a .deh file successfully and generate the corresponding -deh parameter, the user must manually edit the .deh file's extension so that it is exactly "filename.deh".  DEH, Deh, DEh, deH, and so on are not recognized.

Examples: D1DEHFIX made by the guy who did the Minor Sprite Fixing Project, PL2 is Plutonia 2
D1DEHFIX.DEH will fail and generate -file
D1DEHFIX.deh will succeed and generate -deh

PL2.DEH will fail and generate -file
PL2.Deh will fail and generate -file
PL2.deH will fail and generate -file
PL2.deh will succeed and generate -deh

This is a minor issue with a simple workaround for the user.  The user only needs to rename their .deh files to use all lowercase letters in the file extension, then DoomRunner will load them as intended.  I bring this issue up only as an improvement to the end user experience, as modders are the ones who choose whether or not to capitalize their file names, and may do so for personal reasons and/or without informing the user.

This issue primarily affects users who utilize a sourceport / engine that does not load dehacked patches located within the .wad and rely on loading a patch supplied by a mod or map.  Minor fixes such as the D1DEHFIX are intended to be loaded with any map that features the original Doom sprites.

![dehfileexample](https://user-images.githubusercontent.com/71313143/99897830-7c5fc380-2c62-11eb-9e7f-39ae7aab5f20.png)

Edit: fixed grammar / spelling

**Comment by Youda008** [comment]
Thank you for this very detailed report.
I already fixed this here https://github.com/Youda008/DoomRunner/commit/7c0782648b67f6ed93a53f74d6e0077eda024bcd
but did not make a release yet. I will add your suggestion and release it after.

**Comment by Berzasperd** [comment]
You're most welcome.  This is an awesome frontend.  Keep up the good work.

**Comment by Youda008** [comment]
There you go https://github.com/Youda008/DoomRunner/releases/tag/v1.3.3
