### ISSUE TITLE
[Suggestion] Generate -bex parameter for .bex files loaded through the Mods section

### ISSUE THREAD

**Issue by Berzasperd** [Youda008/DoomRunner#28]
This is a suggestion for built-in support for Boom Extended files in the same manner as Dehacked files are handled.  This is a very low priority suggestion, as these patches are usually incorporated into the .wad and loaded by the sourceport / engine.  This change would be almost entirely for legacy support for old maps or specific engines, but I feel it would still improve the user experience.

As of now, a simple workaround is to just use the additional command line arguments field to load such files, as DoomRunner will incorporate the -bex parameter into the final launch command as reliably as any other command.

To complete this addition, the file selection window that appears when adding a mod (the + button) would need the .bex file extension added to the list of defaults.  As of now, the files can still be selected if the user changes the selection to All Files (*) but they will generate a -file parameter instead of -bex.

![bexselectionexample](https://user-images.githubusercontent.com/71313143/99898258-b2527700-2c65-11eb-8f06-d460f88fc6ac.png)

**Comment by Youda008** [comment]
added to the recent hotfix release
