### ISSUE TITLE
Final launch command adds both -deh and -file parameter to .deh files

### ISSUE THREAD

**Issue by Berzasperd** [Youda008/DoomRunner#29]
This issue appears to have arisen from the recent change to the .deh file loading through the Mods section.  DoomRunner now generates the -deh and -file parameter for each singular .deh loaded.  This does not appear to affect the new .bex functionality.

This is a very low priority issue, as the sourceports I have tested already ignore .deh files passed through the -file parameter.  That being the case, the sourceport will still load the .deh patch as instructed by the -deh parameter and continue to ignore the -file one.  There is no loss of functionality with the new changes in version 1.3.3, and the only effect is a longer final launch command.

I briefly attempted to look into the source code, but my understanding of C++ is extremely rudimentary.  I can only speculate that the new code passes the added file through both the first IF condition and the final ELSE for some reason.

![doubledehexample](https://user-images.githubusercontent.com/71313143/100011832-ee85f480-2d97-11eb-95d9-a287b47d9a2e.png)

**Comment by Youda008** [comment]
I'm sorry, i'm tired these days. I screw it up.

**Comment by DanilaSpevak** [comment]
> I'm sorry, i'm tired these days. I screw it up.

It's OK, don't be hard to yourself. You're doing great, especially given the circumstances. Take your time, have some rest, you deserve it.

**Comment by Youda008** [comment]
I re-released 1.3.3 again with the fix, because i would have hard time justifying 1.3.4 because of missing `else` keyword.

**Comment by Berzasperd** [comment]
Don't worry, my friend.  I feel bad that I can't do more than just act like a play tester for these things.  It just so happens that I really like DoomRunner as a program.  I wanted to post these issues here so that other users knew what was going on as well.  The fact that you looked at them and worked on them means a lot to me.  I'm also trying to learn how to use GitHub better, and I figured this was a good way to start.

The Doom Community appreciates your hard work.
