### ISSUE TITLE
[Bug] IWADs with IWAD/IPK3/PK3 extensions not recognized

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#3]
With v0.9, choosing .IWAD, .IPK3 or .PK3 extensions as IWADs is no longer possible. This is however required for The Adventures of the Square (square1.pk3) and the standalone release of REKKR (rekkrsa.iwad). Also manually adding files does not work since the file filter now only allows .wad files.

In general, the launcher should support the following formats to be 100% ZDoom compatible:
- IWADs: .wad, .iwad, .pk3, .ipk3, .pk7, .ipk7
- Mods: .wad, .pk3, .zip, .pk7, .7z

**Comment by Youda008** [comment]
Thanks. I did not know that some doom mods use extension .iwad or .ipk3. I'm now working on the Compatibility Options, but right after than i'll fix these extensions.

**Comment by Youda008** [comment]
This bug should be now fixed in release 1.0. Thank you.
