### ISSUE TITLE
Multiple checkboxes in mods list

### ISSUE THREAD

**Issue by DanilaSpevak** [Youda008/DoomRunner#30]
In mods list you can select multiple items, and most functions correctly apply to all selected elements (remove, move up/down). But when I press Space button, the flag only changes for the element that was selected last. Wouldn't it be more logical to change the flag for all selected elements?

**Comment by Youda008** [comment]
If i figure out how, i will do it. This is the default behaviour.

**Comment by Youda008** [comment]
Done. Will be part of next release.
