### ISSUE TITLE
Put options.json in QStandardPaths::AppConfigLocation

### ISSUE THREAD

**Issue by PopeRigby** [Youda008/DoomRunner#34]
Its current location on Linux (`/opt/DoomRunner`) causes permission issues, which makes DoomRunner unable to write to `options.json`. 

If you set the config location to `QStandardPaths::AppConfigLocation`, then Qt will handle it for you, and should put it in the right directory no matter the OS.

Here's the relevant Qt documentation: https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by Youda008** [comment]
Alright, i will use the standard system paths for storing options.json, but only on Linux, on Windows it's an overkill for such small and simple app. Even GZDoom stores its config in the directory of its executable.

**Comment by Youda008** [comment]
Done. Will be released soon.
