### ISSUE TITLE
Create new config files from preset config file

### ISSUE THREAD

**Issue by PopeRigby** [Youda008/DoomRunner#35]
You should be able to create new config files from a preset config file. Then you can more easily have a config file for each game mod preset without having to modify the same settings every time you want a new one.

**Comment by Youda008** [comment]
I'm not sure i understand the request.
Do you want the DoomRunner to generate new ZDoom config files? Or do you want it to make a copy of an existing one? Or something totaly different?

**Comment by PopeRigby** [comment]
> Or do you want it to make a copy of an existing one?

Yeah, basically this. You could just duplicate it it your file manager, but it's easier if there's just a plus button in DoomRunner to create one seamlessly.

**Comment by Youda008** [comment]
So basically you want a button "Clone exiting config" somewhere next to te config combo-box. That can be done. Though i will probably do it, when i replace the button symbols with some more intuitive icons.

**Comment by PopeRigby** [comment]
Exactly. Sorry for explaining it in such a confusing way.

**Comment by Youda008** [comment]
Done. Will be part of next release.
