### ISSUE TITLE
Treat mod directory similar to map directory

### ISSUE THREAD

**Issue by PopeRigby** [Youda008/DoomRunner#36]
I have a few mods that I load almost every time, and it's a bit tedious to have to add them one-by-one through the file selection menu. The map directory has a good way of handling it, where each map in the directory is shown automatically and you select the one you want. I think the mod directory could be handled in a similar way, but instead of selecting one map, you can click the checkbox next to the mod.

**Comment by Youda008** [comment]
The problem with this approach is that when you display a content of a directory and just add checkboxes in front of them, then you can't change the order of loading, because in the directory they are always sorted alphabetically.

**Comment by PopeRigby** [comment]
> because in the directory they are always sorted alphabetically.

Can you make it not sort alphabetically?

**Comment by Youda008** [comment]
I've already tried this approach long time ago in a predecessor called DoomModLauncher
![obrazek](https://user-images.githubusercontent.com/20306543/105391505-782c3400-5c1a-11eb-9ff9-8ef39ba1637e.png)
It ended up as disaster, it caused more issues than it solved and people who tried it didn't like it.
I'm sorry, but i won't do this one. You can ease up repetitive adding of mods by drag&drop from file manager.

**Comment by PopeRigby** [comment]
Fair enough. Being able to load entire directories will make it easier.
