### ISSUE TITLE
[QoL] Multiple Selection  when adding new mods

### ISSUE THREAD

**Issue by DanilaSpevak** [Youda008/DoomRunner#38]
When I add mods via "Add new mod file", sometimes there are a few of them in the same folder. It would be more convenient if I could select them at once, but as of 1.4 file selection dialog is single-file only. BTW, multiple drag'n'drop works perfectly.

**Comment by Youda008** [comment]
I didn't change it, it was single-selection all the time. But i will do it after i figure out how.

**Comment by Youda008** [comment]
Ok, that was actually easy. Will be part of next release.
