### ISSUE TITLE
List AUR link in the README

### ISSUE THREAD

**Issue by PopeRigby** [Youda008/DoomRunner#39]
I'm maintaining the DoomRunner package in the [AUR](https://aur.archlinux.org). Do you mind putting the link in the README so Arch Linux users can get DoomRunner easier? Here it is: https://aur.archlinux.org/packages/doomrunner/

**Comment by Youda008** [comment]
That's awesome! I've never thought my app would make it into an official repository. I modified the README. Thank's a lot.

**Comment by PopeRigby** [comment]
Heh, it's not really official (Arch *User* Repositories), but I'm glad to be a help (:

**Comment by rollingmoai** [comment]
@poperigby The AUR package does not make a desktop entry for the application, can you please fix this?

**Comment by poperigby** [comment]
@rollingmoai This would be easiest if a desktop file was included in the repository. I can make a PR.

**Comment by poperigby** [comment]
I'll just have to wait for a new release to include it in the AUR.

**Comment by Youda008** [comment]
True. DoomRunner now uses `~/.config/DoomRunner/` to store its files on Linux, and it's a single executable, so it should be able to run from standard binary directories.

**Comment by poperigby** [comment]
> Thank you so much for maintaining this package!

Happy to do it :slightly_smiling_face:

> Looking over the PKGBUILD, is it still necessary to install to /opt? https://github.com/Youda008/DoomRunner/issues/34 seems to fix the 'issue' of DoomRunner creating its config in the same directory as the executable. Maybe I'm missing something, but it seems that there's nothing that would cause problems if we installed to /usr/bin.

Great! I just updated the PKGBUILD. It seems to work on my system, but do you mind testing it?

**Comment by poperigby** [comment]
Thanks for testing. Would you like to submit a PR with those changes, or should I?

**Comment by Youda008** [comment]
> @Youda008 It looks like DoomRunner is still installing a binary to `/opt/DoomRunner/bin/DoomRunner` for some reason, as well as installing one in `/usr/bin`. Any idea why that would be happening?

It was you who made these changes 🙂 https://github.com/Youda008/DoomRunner/pull/32, https://github.com/Youda008/DoomRunner/pull/33

**Comment by poperigby** [comment]
@Youda008 Do you mind pushing a new minor version with @Throun's PR? I accidentally modified the AUR build already, so it's currently not working.

**Comment by Youda008** [comment]
I'm sorry for answering so late. I have been extremely busy the last 2 months.
I will attempt to release a new bug-fix version soon with the current build settings.

**Comment by poperigby** [comment]
No worries. Do it whenever you have time.

**Comment by Youda008** [comment]
@poperigby What commands do the users need to add this repository and install this package? I would like to add that to the README too.

**Comment by poperigby** [comment]
They can run this series of commands:

```
git clone https://aur.archlinux.org/doomrunner.git
cd doomrunner
makepkg --syncdeps --install --rmdeps --clean
```

To update, they can just run `git pull` in the package repository, and then `makepkg --syncdeps --install --rmdeps --clean` again. 

Additionally, you could tell them how to do it with an AUR helper, like [paru](https://github.com/morganamilo/paru). 

Here's a draft:

> **Installing `doomrunner` AUR Package**
> 
> To install `doomrunner` on Arch Linux, follow these steps:
> 
> **1. With [`paru`](https://github.com/morganamilo/paru) AUR Helper (Recommended)**
> 
> ```bash
> # Install `paru` if you don't have it
> 
> # Update your system
> sudo pacman -Syyu
> 
> # Install `doomrunner` using `paru`
> paru -S doomrunner
> ```
> 
> **2. Manual Installation**
> 
> ```bash
> # Clone the `doomrunner` AUR repository
> git clone https://aur.archlinux.org/doomrunner.git
> 
> # Navigate to the cloned directory
> cd doomrunner
> 
> # Review the `PKGBUILD` file (Optional)
> # Make sure there are no suspicious lines
> 
> # Build and install the package
> makepkg -sirc
> ```
> 
> Please exercise caution when using AUR packages and review the `PKGBUILD` file to ensure safety.
