### ISSUE TITLE
[Bug] Mod deletion while selected

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#41]
If you have a mod selected for being loaded (checkbox checked) in section "6. Add mods" and delete the file manually (before removing it from the launcher list first), DoomRunner fails to take the file out of the list. You will keep getting a popup telling you it cannot find the removed file, even after closing and reopening the launcher. 

The only solution right now is to edit options.json and remove the problematic entry.

**Comment by Youda008** [comment]
I think this is the same issue as the previous one https://github.com/Youda008/DoomRunner/issues/40
I hope i will get back to this project at the end of summer and fix :all_the_things:

**Comment by Youda008** [comment]
Fixed. Will be part of next release soon.
