### ISSUE TITLE
Unset 'directory with maps' side effects

### ISSUE THREAD

**Issue by proydoha** [Youda008/DoomRunner#44]
Version 1.5
When 'directory with maps' is not set to any folder all files that I drag into DoomRunner are also "loaded as map" resulting in accidental double loading of the same files. Workaround that I've found is to set  'directory with maps' to an empty folder instead of leaving it empty and load maps as any other mod.

There is also no horisontal scroll in 'Select mappack' list and when DoomRunner window is set to its minimum size you may not notice that you're double loading your files on accident.

**Comment by Youda008** [comment]
Thanks. I know about this, it's been reported on the forum. It's already fixed in master. I will give people 1-2 more days to try it out and report bugs and then i will make a bugfix release.
