### ISSUE TITLE
[QoL] Open file location for added mods

### ISSUE THREAD

**Issue by proydoha** [Youda008/DoomRunner#45]
It would be nice if it were possible to rightclick on an item in 'Add mods' list and select 'Open file location' since DoomRunner does not include file/directory paths in the list.

**Comment by Youda008** [comment]
Hm, this is bigger problem than i thought. I made it working on Windows, but i cannot test it on Mac and it will definitely not work on Linux.

**Comment by Youda008** [comment]
Correction: It will work on Linux, but it will not highlight the selected file, it will just open the directory in file manager.
