### ISSUE TITLE
[Suggestion] Dark Theme for Windows

### ISSUE THREAD

**Issue by Berzasperd** [Youda008/DoomRunner#47]
This is the obligatory request for a dark theme for this program that runs on Windows operating systems.  No modern application can be considered truly feature complete without the option to switch between a blindingly bright and dismally dark interface color scheme. /mild sarcasm

![doomrunner_theme_compare](https://user-images.githubusercontent.com/71313143/143731978-92911f04-c832-417f-a030-6a60ac13edff.jpg)

This is a (really) rough side by side comparison.  On the left is a screen grab on Windows 10.  On the right is a similar screen grab in Garuda Linux with a(n) Xfce desktop environment.  Interestingly enough, Doomrunner's windows, text, and highlights will all adapt to the styles chosen in the Linux distro.  It looks even better with KDE Plasma and the Win 9.x style.  In Windows, the only thing you can change easily is the Active Title Bar color (and less easily the inactive color).

Since I am trying to switch to using Linux primarily, this issue won't affect me too much, but I still figured I would put it on the board because it is the one of the only things that might swing the average users' decision when it comes to picking a frontend for their Doom and Doom-esque games.  I consider this to be the best in terms of design, features, and user experience, but ones like Arachnotron offer a great deal of visual flair.

I am not sure what approach you should take when it comes to dealing with Windows and the sort of "hardcoded default" window colors.  I haven't tested if pre-Aero themes can affect Doomrunner's appearance, but most users (myself included) would not be able to forsake desktop composition and certain features just for one program.  I would say that even a simple toggle between one pre-built light and dark theme would be enough.  Being able to pick custom colors can be fun for some, though.

**Comment by Youda008** [comment]
I haven't found an easy way to do this, i thought Qt would maybe adapt to the selected Windows 10 theme, but it doesn't.
I found this issue from 2018, it has been ignored since then, but 26th July it was switched to `In Progress` so maybe soon? 🙏 
The only other alternative would be to manually set colors of all widgets, but that would then bypass and ignore the Linux graphical manager preferences.

**Comment by keatit71** [comment]
Doomrunner being one of the few qt applications i have with only light theme it would be nice to have a dark theme. I found this thread talking about dark them support for windows and there seems mention of code you can add as well as something called qtimer which can automatically make the qt program light or dark depending on the windows setting.

**Comment by Youda008** [comment]
Alright bois, dark theme is comming!

It was a hard battle against Microsoft / Windows, but i won. I had to made some ugly hacks to set the window title bar to black. It's not perfect, it works only on Windows 10 20H1 or newer, and sometimes it glitches out, but it's good enough.

Will be part of 1.7.

**Comment by keatit71** [comment]
When will 1.7 be coming out?

**Comment by Youda008** [comment]
Can't promise. I still need to resolve the other issues reported here, at least the CPU load and wrong GZDoom started.
Maybe in 2-3 weeks?

**Comment by Youda008** [comment]
Version with dark theme is ready for beta-testing [DoomRunner-1.7-preview2-Windows-64bit.zip](https://github.com/Youda008/DoomRunner/files/9997540/DoomRunner-1.7-preview2-Windows-64bit.zip)

**Comment by keatit71** [comment]
Dark mode looks good, do you plan to add a toggle button or is it controlled by windows dark mode being on or off?

**Comment by Berzasperd** [comment]
Dark Mode is looking top notch.  Nice two-tone grey, text and buttons all stand out.  The "selected file / highlight" is super visible for me (2A82DA RGB hex, dimmed sky blue).  The only thing that looks slightly off is the Separator color (A0A0A0 RGB hex, mildly bright grey).  Granted, this does give them the sort of contrast that makes them useful as separators, so I think I'm fine with it unless you wanted to add custom colors to the separator.  All in all, I really like it.  Personally, I think the rounded border squares around the sharp menu squares is fine as well.  I'm sure there's a discussion to be had when it comes to style guides and such.

This is just a first impression, which is great so far.  I'll try to do some real testing to see if something jumps out.

@keatit71 : Right now, the options for the theme are System default, which matches up with your Windows setting, and Dark (override), which will set it to dark if your system theme is light.  There isn't a Light (override) option in the 1.7 preview 2 beta release (at least not that I saw).  Right now the toggle button is in the Initial Setup screen, under Menu.

**Comment by Berzasperd** [comment]
After peeking around various menus for a bit, I've only found 2 things to comment on with the current state of the dark theme.

1: The hyperlinks in the About sub-window are hard to read against the darker background.  For me at least, I think this is because they use Blue 255 (0000FF rgb hex) as the primary color, which I have always had trouble reading against dark backgrounds.

2: There are less differences between Active and Inactive (or disabled) elements in the More options tab.  In v1.6.5, an active field, dropdown menu, or button will be distinguished by some or all of the following: border color, text background color, text color.  The beta dark mode only distinguishes these by changing text color.

Number 1 isn't an issue in light theme, since full blue is fine there.  I don't remember if that is a Windows issue for default colors on hyperlinks.  If it is, I will fix that on my end.  Number 2 is more of a point about UI design.  Should all of those elements change for active / inactive fields?  Is the contrast between them sufficient?  I don't really know and I don't have any proposals for that right now.  I find it well within my own threshold of being usable and not confusing, but that is a personal thing that you would need more people to weigh in on to see if it is something that really needs to be changes.

As things are right now, I think everything is looking great.  I'm not sure if I want to actually suggest a Light (override) option or not, but maybe someone else can do that.  I like having all my apps as dark as I can get away with.

**Comment by Youda008** [comment]
Those are exactly the type of problems, for which i didn't want to make a dark theme 😕
Designing a full color palette so that everything looks good under all circumstances is a hard task for a pure programmer like me.
But i already promissed it, so i have to cope with it now.

The hyperlinks are problematic.
I already tried to change their color https://github.com/Youda008/DoomRunner/blob/master/Sources/ColorThemes.cpp#L93
but Qt seems to ignore this. Even when i try to change that color in Qt Designer, it does not work
![obrazek](https://user-images.githubusercontent.com/20306543/202895377-33917d6d-f249-4022-9fe5-d2b75f89cba5.png)
and i currently don't know what to do with it.

The active/inactive differentiation should not be a problem, though i can't guarantee it will look beautiful.

**Comment by Youda008** [comment]
Regarding 2:
I booted up Kubuntu to see how the official dark color palette looks like there and this is the comparison between their dark palette and my (stolen) dark palette.
![KDE-Dark-Breeze](https://user-images.githubusercontent.com/20306543/203144172-dc85f2a7-c95d-48a8-afa4-536a8819ce7a.png)
![KDE-Dark-Override](https://user-images.githubusercontent.com/20306543/203144177-247f03dd-2ba9-44e6-81f5-4d7d6995ee68.png)
If you put them side-by-side, you can see there is basically no difference between how they display disabled items vs how i display disabled items, with the exception of disabled checkbox text, which i'm gonna fix.

So all in all i would say it does not need more tunning, maybe the separators if i figure out how to overcome a slight implementation problem.

**Comment by Berzasperd** [comment]
Following up on the hyperlink situation, I tried using Windows 10 High Contrast theme to change the color of links, and the ones inside Doomrunner are still not changed by it.  High Contrast changes links in Windows 10 Settings and on Waterfox (web browser based on Firefox), but for some reason, Doomrunner's are resistant to even that level of change, so that situation is even more of a mystery than before.

I was going to take a look at things on Linux side, but I switched from Garuda (which was Arch based) to Mint (Ubuntu) recently and still haven't figured out what to do with the Doomrunner file from the download page here.  I'm still a beginner for Linux stuff, so I'll have to come back to that later.

And yeah, for the active and inactive fields, I think you got it pretty well covered.  I only mention things like that because it falls under Accessibility concerns.  My only vision impairment is that I'm near-sighted.  Contrast and colors are fine for someone like me.  Unfortunately, designing for the multitude of other visual impairments is a huge undertaking.

I know posting to random issue comment thread isn't the best place for broad discussion, but I just wanted to say that I think the work you've done so far is fantastic.  This is **THE** frontend I like the most out of the 4 or so I've tried.  When I post these long-winded issues, I'm not trying to criticize your work or make you compromise on your vision or where you want this project to go.  All I want to do as a casual tester is to lay out everything I've found for everyone to see and open it up to discussion.  If someone else comes in to agree or disagree with something, I don't mind.  A lot of things can just come down to personal preference.  My goal is just to bring attention to something that may have gone unnoticed or to bring people together to test out things in ways that I didn't think of.  I didn't want to come across as overly pushy for these things.

**Comment by Youda008** [comment]
Thank you for this dedication. I'm glad for any beta testers, because despite me using the launcher myself, i don't use it as many different use-cases of the users combined, and it's not in my power to test all possible scenarios in the Doom modding world. So there will inevitably be bugs in the features i don't use myself, and therefore i welcome any issue report.

I think i solved the hyperlinks. In Qt, if you add a widget with text that contains HTTP link, it automatically generates `<a href="https://github.com/Youda008/DoomRunner"><span style=" text-decoration: underline; color:#0000ff;">` and that overrides any styles and themes user might want to set. So this HTML color definition needs to be manually modified by the code each time such dialog is opened.

**Comment by Youda008** [comment]
It's out.
