### ISSUE TITLE
[Suggestion] Add support for more ports

### ISSUE THREAD

**Issue by matttcooke** [Youda008/DoomRunner#48]
The only blocking point for using this launcher with eg. PrBoom, dsda-doom, and Crispy Doom seems to be with the "file" arguments. 

ZDoom ports expect a "-file" flag before each file argument, but the ports mentioned above expect a single "-file" flag with a list of file arguments after it.

Would it be possible to allow configuring how file arguments get flagged per engine?

**Comment by Youda008** [comment]
That would be possible, yes. Or try to auto-detect arguments style by port executable name.

**Comment by Youda008** [comment]
According to ZDoom wiki, the syntax `-file file.1wad file2.wad file3.wad` is also supported. So i will just convert everything to that.

**Comment by Youda008** [comment]
Done. Will be release soon™
