### ISSUE TITLE
Separators in Mods and Presets list

### ISSUE THREAD

**Issue by DanilaSpevak** [Youda008/DoomRunner#49]
In ModOrganizer 2 I've seen a nice idea - visual separators for mod lists. They're added via separate buttons and are used to visually separate mod groups. Right now I'm using workarounds - empty presets and empty folders, but it would be nice to have proper visually distinguishable separators which are edited via GUI.
This is how it looks in MO2:
![image](https://user-images.githubusercontent.com/42034406/147479674-2e2f7c40-ebb7-4e71-b8d7-8bfb5ccda705.png)

And this is how the look in DoomRunner:
![image](https://user-images.githubusercontent.com/42034406/147479735-badc66a6-ed27-45af-b54f-f301e40d8545.png)

**Comment by Youda008** [comment]
Alright, that looks doable.

**Comment by Youda008** [comment]
Ok, that was actually much more difficult than i thought. Expect the first version to be buggy. Will be released soon.
