### ISSUE TITLE
Will you implement the ability to open mods from zip? 

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#50]
hi , 
it's nice to be able to open maps from zip.
is there a possibility to open mods from zip?
will you implement it?
thank you

**Comment by Youda008** [comment]
It should be already work, does it not? The "zip" is already in the file filters.

**Comment by buvk** [comment]
I think it depends on the source port.  For example, GZDoom supports loading zip files, however, Crispy Doom does not.

**Comment by Youda008** [comment]
Ok, closing, because DoomRunner can already handle zip files, it only depends if the engine supports it.
