### ISSUE TITLE
[Suggestion]Option to pipe zdoom console output to the launcher

### ISSUE THREAD

**Issue by D3X1KAXYZ** [Youda008/DoomRunner#51]
I have been using ZDoom Executer for some time now and have been looking for something a little more up-to-date. DoomRunner looks to be perfect for that, however as modder, one feature that draws me to ZDE over other launchers (this one included) is the feature to pipe console info out of zdoom and into ZDE. It is great for debugging issues.

**Comment by Youda008** [comment]
ZDoom and GZDoom does not output anything to the stdout and stderr. Are you on Linux?

**Comment by Youda008** [comment]
Ok, on Windows you need to add `-stdout` for it to start logging to terminal.

This was a hell of a work, but a first version of a engine output window is in master. Can you can you compile it and try it out before i made an official release?

**Comment by Youda008** [comment]
Here is a binary if you want to beta-test it before official release

[DoomRunner-1.6-preview-Windows-64bit.zip](https://github.com/Youda008/DoomRunner/files/9569949/DoomRunner-1.6-preview-Windows-64bit.zip)

**Comment by Youda008** [comment]
Released.
