### ISSUE TITLE
[Feature] Master Levels support

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#55]
The PrBoom+ Launcher has a nice feature that lets you launch the Master Levels directly. It's mostly warping to the right map slot directly depending on your selection (e.g. Blacktwr.wad as MAP25 etc), so you don't have to know which map to set when warping. 

Would be nice to have this here as well in some form, maybe an extra tab called "Master" which only shows up if you set up a path that points to the wad files.

[Map IDs can be found here.](https://doomwiki.org/wiki/Master_Levels_for_Doom_II)

**Comment by Youda008** [comment]
Alright, time to sort this mess up.
Don't you wanna learn C++? 😄 The amount of demanded work is getting kindof overwhelming.

**Comment by NightFright2k19** [comment]
I hope that was a rhetorical question. xD

**Comment by Youda008** [comment]
Unfortunatelly not. I'm getting slightly burned out of this project, the requests just keep comming. And i would already like to spend my effort and creativity elsewhere. I will try to sort out the current wave of issues, but after that ... it's time to search for a new maintainer guys.

**Comment by NightFright2k19** [comment]
Not all of the open request here are super important. However, ports like Crispy Doom or Woof not being able to load multiple pwads at once by default (unless you edit the launch commands manually) is definitely one of the bigger annoyances.

**Comment by Youda008** [comment]
Uff, well this feature would require either to have a manually maintained list of known wads and their corresponding starting level, or be able to read the content of the wad and find out what the first level is.
The first solution will never be complete and people will keep asking to add new and new wads.
And the second is a lot of work to do.

**Comment by NightFright2k19** [comment]
Or you just limit support to these specific wad files via checksum and ignore all the rest, as that PrBoom+ launcher does (I think).

**Comment by Youda008** [comment]
Then give me the list. I had the MasterLevels before, but they got lost probably when i was moving to another flat.

**Comment by Youda008** [comment]
@NightFright2k19 If you want this feature to get into 1.6, you need to provide me a list of WADs and their corresponding starting levels. I cannot do it myself, since i lost the Master Levels.

**Comment by NightFright2k19** [comment]
Will do right away when I am back from vacations. Thanks for considering this, pal!

**Comment by Youda008** [comment]
Sorry, i did not receive email notification about this one. I will add it to 1.6.1.

**Comment by Youda008** [comment]
Implemented in master branch.

**Comment by NightFright2k19** [comment]
Excellent! Could you maybe compile a test build so I can check it out or is the new version coming soon, anyway?

**Comment by Youda008** [comment]
Here: [DoomRunner.zip](https://github.com/Youda008/DoomRunner/files/9649748/DoomRunner.zip)

**Comment by NightFright2k19** [comment]
OK, first observation is that this obviously doesn't work if Launch Mode is set to "Default", but I guess that's normal (and also wouldn't work since no difficulty level has been selected). Otherwise it chooses the map slot correctly when selecting the wad.

Apparently, any non-MAP01 maps launch just fine. However, for some reason, the MAP01 replacements use the setting of the last non-MAP01 map, i.e. they don't work.

Example: You launch virgil.wad, launcher changes to MAP03 correctly. Then you switch to attack.wad. Launcher SHOULD switch to -warp 01, but stays at -warp 03. Maybe you have to explicitly define the remaining maps (attack.wad, canyon.wad, catwalk.wad, combine.wad, fistula.wad, garrison.wad, manor.wad, paradox.wad, subspace.wad, subterra.wad, ttrap.wad) for the MAP01 warp slot.

**Comment by Youda008** [comment]
Hm, only a combination of Default mode and joining a multiplayer server as client should disable the compat level
![obrazek](https://user-images.githubusercontent.com/20306543/192459875-9a3e0f11-f7d5-49d2-afca-f08bfc929237.png)
because this should be server-controlled and if client enables different options, desync will occur.
Singleplayer Default mode should have it normally enabled.
![obrazek](https://user-images.githubusercontent.com/20306543/192460146-9e149d06-e6ba-4bef-a02a-a380be38305f.png)
Did you get different results somehow?


Ok, i agree that those MasterLevels that start from MAP01 should be included too, otherwise the previous values from previously selected MasterLevel stays there, which is incorrect.

**Comment by NightFright2k19** [comment]
Alright then. Should be easy to fix, I guess. Will gladly test again once you have implemented the fix, but I think it's almost impossible to still run into problems after that.

**Comment by NightFright2k19** [comment]
A nice bonus would be to also have support for the other levels from the Master Level creators which were not considered by id for release. These maps have seen some increased interest lately with user compilations which include them, also since this puts the Master Levels in some greater context (many of them are part of some series).
I would consider adding those to the launcher a "nice to have" thing, especially since the feature is already in. 

The missing levels would have the following map slots (this list is complete, there are no more):

**MAP01**
anomaly.wad
cdk_fury.wad
cpu.wad
device_1.wad
dmz.wad
e_inside.wad
farside.wad
hive.wad
mines.wad
trouble.wad

**MAP02**
dante25.wad
derelict.wad

**MAP03**
achron22.wad
flood.wad
twm01.wad

**MAP04**: watchtwr.wad
**MAP05**: todeath.wad
**MAP06**: arena.wad
**MAP09**: storm.wad
**MAP30**: the_evil.wad

**Comment by Youda008** [comment]
I can add that. That's not a problem.

**Comment by NightFright2k19** [comment]
Amazing! I promise I won't ask for more (also since there isn't anything else).

Come to think of it: Does your launcher support level warping for Sigil? It has E5M1-E5M9.

**Comment by NightFright2k19** [comment]
It now appears all the Master Levels launch properly. Well done!

**Comment by Youda008** [comment]
And SIGIL is IWAD or how does it work, that it has 5 episodes?

**Comment by NightFright2k19** [comment]
SIGIL is a pwad which you load after doom.wad, pretty much like the Master Levels work with Doom II, with the main difference being that it is a full episode. 

I think the easiest way to implement support is just to add E5M1-E5M9 to the "Launch selected map" dropdown menu when doom.wad is selected. It just won't work when SIGIL_v1_21.wad is not loaded.
