### ISSUE TITLE
[Feature] Complevels for PrBoom+/Woof

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#56]
For PrBoom+ or similar (like Woof), there is the -complevel parameter which is quite important. It would be good to have it available in the launcher as well, ideally only showing when PrBoom+/Woof/etc is chosen as a sourceport.

(I am aware that there is a compatibility options tab already, but these settings are very detailed and I think everybody would prefer setting up certain complevels directly without having to tic every option related to the desired level. Rather like a dropdown menu with preset complevels instead of having to enter numbers anywhere.)

These complevel selections should be available:
2 (Doom 2)
3 (Ultimate Doom)
4 (Final Doom)
9 (Boom compatible)
11 (MBF compatible)
21 (MBF21 compatible)

**Comment by NightFright2k19** [comment]
For Woof!, this would be:
-complevel vanilla
-complevel boom
-complevel mbf
-complevel mbf21

**Comment by NightFright2k19** [comment]
Update:
GZDoom recently received the **-compatmode** parameter which works pretty much the same as -complevel, so that should also be considered.

**Comment by sitiom** [comment]
> These complevel selections should be available:
> 2 (Doom 2)
> 3 (Ultimate Doom)
> 4 (Final Doom)
> 9 (Boom compatible)
> 11 (MBF compatible)
> 21 (MBF21 compatible)

Why not just include everything for the sake of completeness 😅

**Comment by Youda008** [comment]
So you are basically asking to have a Compatibility Options presets, with some common ones being there out of the box?
Do i understand it right?

**Comment by Youda008** [comment]
Ah, sorry, i found this page now. https://doom.fandom.com/wiki/PrBoom
So i can basically just copy this table into the code
![image](https://user-images.githubusercontent.com/20306543/186479620-127c8ef1-6d81-4fda-b947-dd7bca3e7c58.png)
and use the number (first column) as a command line argument, and the description (second column) as a hint to the user.

**Comment by Youda008** [comment]
Can you please point me to a forum thread or article about the new gzdoom's parameter `-compatmode`? It's not in the wiki and i can't find how to use it.

**Comment by NightFright2k19** [comment]
That's pretty much it, yeah. Not all of these complevels are really relevant. I haven't seen any mod out there yet which was made for any complevel other than 2-4, 9, 11 or 21.

Regarding GZDoom's compatmode, I think [this wiki entry should cover everything](https://zdoom.org/wiki/CVARs:Configuration#compatmode).

**Comment by Youda008** [comment]
I believe this is done now. Can you please beta test it?

[DoomRunner.zip](https://github.com/Youda008/DoomRunner/files/9543122/DoomRunner.zip)

**Comment by NightFright2k19** [comment]
Sure thing. Just gimme 2-3 days until I am back from my holidays.

**Comment by sitiom** [comment]
> I believe this is done now. Can you please beta test it?
> 
> [DoomRunner.zip](https://github.com/Youda008/DoomRunner/files/9543122/DoomRunner.zip)

I'm trying it, but I'm not sure where I can find the complevels section.

**Comment by sitiom** [comment]
The button is disabled under the standard launch mode
![image](https://user-images.githubusercontent.com/56180050/189628622-44469ed0-4a5f-4ce1-b903-e55604c3fd91.png)

And I don't see it there either
![image](https://user-images.githubusercontent.com/56180050/189628830-e37e1134-3d3b-4ee0-b565-a4e9dc3f0596.png)

I'm testing this with the PrBoom+ engine to be exact.

**Comment by Youda008** [comment]
I'm sorry, i sent you a wrong binary. This should be the right one: 
[DoomRunner-1.6-preview-Windows-64bit.zip](https://github.com/Youda008/DoomRunner/files/9547381/DoomRunner-1.6-preview-Windows-64bit.zip)

Regarding launch mode, as far as i know, the game options and compatibility options only work when you launch a map directly. When you just start the game into a menu, those options are ignored by the engine.

**Comment by sitiom** [comment]
> I'm sorry, i sent you a wrong binary. This should be the right one: [DoomRunner-1.6-preview-Windows-64bit.zip](https://github.com/Youda008/DoomRunner/files/9547381/DoomRunner-1.6-preview-Windows-64bit.zip)

Thanks, found it now:
![image](https://user-images.githubusercontent.com/56180050/189642803-a28ac410-f949-4c5e-9873-5172bda86050.png)

> Regarding launch mode, as far as i know, the game options and compatibility options only work when you launch a map directly. When you just start the game into a menu, those options are ignored by the engine.

I'm not sure about that, I've been using the complevel options in prboom+ without a specific map and it works well. Not sure about zdoom, though.

**Comment by NightFright2k19** [comment]
Couldn't the "Compatibility Options" also be available without having to select a specific map? Like this you always have to jump to at least MAP01 to use the feature. I rather thought it could be set up in general, so that you can still see the title screens etc first.

**Comment by Youda008** [comment]
I have to try in the evening if the compatibility options remain set if you launch the game into a menu and then start an episode from there. The gameplay options (dmflags) definitely get reset.

I don't like the idea of creeping options into the first tab, because for each person something else is important. Someone wants complevel on the first tab, someone wants a save file on the first tab, someone wants a map name on the first tab.
Moving everything to the first tab would produce something like this
![image](https://user-images.githubusercontent.com/20306543/189885696-4e9f42f1-5c99-43ea-bf46-591e0d14e58d.png)
which was my very early idea of a launcher which was rejected by people for being too complex.

The issue with the right command line parameter, Crispy Doom is not supposed to have any complevel options. 
It's neither here https://github.com/fabiangreffrath/crispy-doom/blob/master/README.md
nor here https://manpages.debian.org/testing/crispy-doom/crispy-doom.6.en.html
nor here https://www.chocolate-doom.org/wiki/index.php/Command_line_arguments
nor here https://doomwiki.org/wiki/Source_port_parameters#-complevel_.3Ccompatibility_level.3E
nor here https://doom.fandom.com/wiki/Source_port_parameters
Does it really work?

**Comment by NightFright2k19** [comment]
It's hard to say actually since I don't see any way this is logged in any port, at least not in Woof! or Crispy Doom (which I am using). Otherwise one would need to check how a Boom map behaves if complevel 2 or something else is used, maybe? TBH I am not sure which is a 100% indicator for a wrong complevel (I guess certain map functions won't work, but then I would need to know a map with a section that depends on enhanced features).

**Comment by Youda008** [comment]
For Woof, try this
![image](https://user-images.githubusercontent.com/20306543/189892752-9f029b60-2eb9-462e-aca1-1283eb8f75a4.png)
Because it's not yet in the built-in list of known engines.

**Comment by NightFright2k19** [comment]
Right, that does the trick for woof.exe. Now it chooses -complevel automatically. Thanks for the hint!

**Comment by Youda008** [comment]
Ok, i was wrong. Both gameplay and compatibility options are loaded and applied when the game is launched to menu and then level started from there. The only thing that is reset for every new started "campaign" is the jumping, crouching and auto-aim.

**Comment by Youda008** [comment]
Hm, ok, so there is `-skill` and `+skill` and each behaves differently. Wonderful.
![obrazek](https://user-images.githubusercontent.com/20306543/190263479-4c83e55a-ad1c-4f08-bf10-802761bc37f0.png)

**Comment by Youda008** [comment]
Here's a guy telling me i should use `+map` instead of `-warp`, lol
https://github.com/Youda008/DoomRunner/issues/18

It will need to be engine dependent again.

**Comment by NightFright2k19** [comment]
I didn't test it with all ports, but I know that -warp is used at least in Crispy Doom, PrBoom+, Woof! and GZDoom (since I am using those).

**Comment by Youda008** [comment]
Release candidate 2, with these issues hopefully fixed: 
[DoomRunner-1.6-preview2-Windows-64bit.zip](https://github.com/Youda008/DoomRunner/files/9601615/DoomRunner-1.6-preview2-Windows-64bit.zip)

**Comment by sitiom** [comment]
Complevel does not get applied in the default launch mode:
![image](https://user-images.githubusercontent.com/56180050/191146087-0e538a8e-2a49-46aa-92ea-a721009c4bae.png)

**Comment by NightFright2k19** [comment]
That and it still selects _+compatmode_ when you are actually using a port that does not support the command like that, e.g. Woof.

**Comment by Youda008** [comment]
Ok, thank you both for beta-testing, it really helps 👍 
I'm closing this now because the original issue is resolved.
Open new issue when you find another problem.
