### ISSUE TITLE
Window Sizing in Manjaro Linux

### ISSUE THREAD

**Issue by Gorethirster** [Youda008/DoomRunner#58]
I'm running version 1.5.1 from the AUR in manjaro linux. My monitor is 1366x768 max resolution. When I launch the software, the default window size is too large to fully display and hangs off the bottom of the screen. Even when shrunk to minimal dimensions and set to stay on top of the taskbar, the "launch" button is still unavailable because it is too far down the screen to click.

**Comment by Nefarious296** [comment]
I am having the same problem on KDE Neon. And It doesn't allow for vertical resizing.

**Comment by stubkan** [comment]
Got the same issue, sadly...  
Ubuntu X system, 768p display height.  This being a common resolution, I think support for this should be a minimum.

![image](https://user-images.githubusercontent.com/34361592/179421104-792a53b3-f314-4d93-a5bc-88f8aeb36e2e.png)

**Comment by Youda008** [comment]
Unfortunatelly that's not possible. The minimum height and width is determined by the second tab "Launch options" where the items cannot be shrinked anymore.
Linux graphical systems has always been making troubles, i have KDE and there the launcher also looks unreasonably large compared to the Windows version, but that's a bad design of those graphical systems. On Windows 10 i can shrink the height to 651 pixels.

**Comment by stubkan** [comment]
I am unsure how I fixed it.  Since it was a while ago now...

I suspect it is due to older dependencies, Since it runs correctly on a different, newer linux version, so I updated everything - leading to it working better. Either that, or I used a different packaged executable file.

**Comment by Youda008** [comment]
Good news guys. I was able to shrink the window by additional 15% by moving the Audio and Video options to a new tab.
It now displays correctly in my Kubuntu. Height is still 741 (on Windows 530, lol) so it won't display properly on 1280x720, but on the more common laptop resolution 1366x768 it should be fine.
It will be released as a part of 1.6 version, but you can re-compile it yourself if you want it immediatelly.

**Comment by Youda008** [comment]
Those of you who are limited by the screen size, there is a new option in the launcher settings that might make the launcher little more compact and therefore capable of downsizing to smaller sizes.
![compat_style](https://user-images.githubusercontent.com/20306543/204601565-cf601530-14ca-4c77-bd46-bf83c8239b13.png)

Application style "Fusion" compresses the UI elements little bit more than the other ones and shoud be available in most operating systems and distro.

**Comment by Youda008** [comment]
Managed to squeeze out few more pixels by integrating the multiplayer checkbox into the groupbox heading.
Together with the Fusion style, it should now fit into every monitor.
