### ISSUE TITLE
Ubuntu precompiled binary cannot find libQt5Core dependency with qt5 installed

### ISSUE THREAD

**Issue by stubkan** [Youda008/DoomRunner#59]
I couldnt launch the precompiled binary release, the full message was

./DoomRunner: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by ./DoomRunner)

It seems like it was somehow seeing it wrongly, as I went through installing libqt5core5a which was listed, but failed.
Installed qt5-default, didnt work.
Tried libqt5quickcontrols2-5 libqt5multimedia5 libqt5webengine5 libqt5quick5 libqt5qml5 and a bunch more.  

In the end, I just compiled the source code and that works.

Maybe the precompiled binary needs updating ?

**Comment by stubkan** [comment]
I suspect this might happen if you have an older system - worked out of the box with ubuntu 20.04 but not 18.04 - it may be that the 18.04 source was too old.

**Comment by Youda008** [comment]
That means they probably changed the .so name in the new Ubuntu versions and it linked against wrong one.
I now have Kubuntu 22.04 so i will build it against that one, but then there is a chance it will stop working on the old versions. Oh well.

**Comment by Youda008** [comment]
@stubkan Can you please try the newest release?
