### ISSUE TITLE
Detect whether `-save` or `-savedir` should be used

### ISSUE THREAD

**Issue by sitiom** [Youda008/DoomRunner#60]
Boom and its derivatives use `-save` instead of `-savedir` to specify the save directory. See [Source port parameters](https://doomwiki.org/wiki/Source_port_parameters) in the Doomwiki:
![image](https://user-images.githubusercontent.com/56180050/181915163-6d61228a-0e85-4c7a-9e35-985043b62dba.png)

Related: #48

**Comment by Youda008** [comment]
Done. Will be released soon.

**Comment by sitiom** [comment]
@Youda008 You should be also accounting for [`prboom-plus`](https://doomwiki.org/wiki/PrBoom%2B) and [`dsda-doom`](https://doomwiki.org/wiki/DSDA-Doom).
