### ISSUE TITLE
Loading multiple PWADs in Crispy Doom

### ISSUE THREAD

**Issue by buvk** [Youda008/DoomRunner#62]
In order to properly load multiple PWADs in Crispy Doom, Crispy Doom must be launched as follows:

"crispy-doom.exe" -file "pwad1.wad" "pwad2.wad"

DoomRunner launches as follows (this causes issues):

"crispy-doom.exe" -file "pwad1.wad" -file "pwad2.wad"

**Comment by Youda008** [comment]
Same as https://github.com/Youda008/DoomRunner/issues/62 Already solved.
