### ISSUE TITLE
[Feature] a window at the bottom for screenshot preview.

### ISSUE THREAD

**Issue by Caiuzx** [Youda008/DoomRunner#68]
thank youda008 for this little program that is helping me get my mods going.
I noticed that you have started working on it and the passion never ends.
It would be nice if you would plan to put a window at the bottom of the program , which would read the files in the screenshots folder and do the preview . If one clicks it opens the screenshot .
Thank you again for the program you made. There is no program on internet. Not even zdl, because there are presets in yours.

Translated with www.DeepL.com/Translator (free version)

**Comment by Youda008** [comment]
Sorry, i don't think i will do that. It does not even fit into the overall launcher design.
