### ISSUE TITLE
[Feature] automatically seperate save paths for presets

### ISSUE THREAD

**Issue by ibin7777** [Youda008/DoomRunner#69]
There's already existing function of alternative save path, What I'm refering to is the ability to automatically create save directory for each preset, that way it saves the effort of manually creating different save folders.

Logically speaking, this requires a setting to enable a global saving directory, then another setting to enable seperate saves by preset into sub-folders.
If it works out, should be something look like this:
![image](https://user-images.githubusercontent.com/64576479/189719686-5f48fd75-1550-413c-a991-32fcd5d7bece.png)
And in the save folder it will be like this:
![image](https://user-images.githubusercontent.com/64576479/189719756-47f87e58-d8a4-43f6-9b0d-2fe6845cc7ac.png)

sorry for my low quality photoshop, I'm no developer...
But as you can see it would be a very nice implimentation, that way you'll no longer see any of the saves from other presets.

**Comment by Youda008** [comment]
I'm sorry, but i have to scale down the development, because this is really draining me out.

But you can do most of this yourself without any changes, by allowing different save directories for each preset
![image](https://user-images.githubusercontent.com/20306543/189889415-e50930d1-621f-487e-bc35-8dfb26c029e4.png)

The Doom engine will automatically create the directory if it doesn't exist. All you have to do manually is write the directory name to the launcher.

**Comment by Youda008** [comment]
I implemented a light version of your request
![obrazek](https://user-images.githubusercontent.com/20306543/191614552-37793197-c57b-4e47-b49e-47bf76c76fbc.png)
It will derive save directory name from the preset name, but the base director is always engine directory, because it was easier.

**Comment by ibin7777** [comment]
> I implemented a light version of your request ![obrazek](https://user-images.githubusercontent.com/20306543/191614552-37793197-c57b-4e47-b49e-47bf76c76fbc.png) It will derive save directory name from the preset name, but the base director is always engine directory, because it was easier.

Thank you the the effort!
That looks amazing, that light version you described is more than enough.
And yes, I completely agree that base director should be engine oriented.

Looking forward to the next release.

**Comment by Youda008** [comment]
Released. Write me if it doesn't work as expected.
