### ISSUE TITLE
Compatibility level doesn't work in GZDoom.

### ISSUE THREAD

**Issue by TwinGalaxy** [Youda008/DoomRunner#72]
You used +compatmode (level) and not -compatmode (level). +compatmode looks like it works but when the game boots up with that parameter, it says the compatmode is the level you chose, but doesn't actually change the flags accordingly. It's a weird gzdoom bug that they added the -compatmode parameter as a workaround for.

**Comment by Youda008** [comment]
Sorry i didn't know that. I was searching for it, but i couldn't find any description or documentation. Is there a thread about it? It is specific to GZDoom?

**Comment by TwinGalaxy** [comment]
To my knowledge, yes. GZDoom uses -compatmode while something like PrBoom uses -complevel iirc. GZDoom is just weird as you HAVE to use -compatmode and not +compatmode for it to actually work.

**Comment by Youda008** [comment]
Where did you learn this? And what about ordinary ZDoom?

**Comment by TwinGalaxy** [comment]
From some quick testing, it doesn't correctly set the flags for ZDoom either. It was expressed in 4.8's changelog for GZDoom.
https://forum.zdoom.org/viewtopic.php?t=75532
"add -compatmode for setting a compatibility mode on startup as a replacement for +compatmode not working as intended."

**Comment by Youda008** [comment]
Ok, so it's basically GZDoom 4.8+ only, other non-PrBoom engines are screwed.

**Comment by TwinGalaxy** [comment]
Yeah, seems so unfortunately :/, I don't think there's a way for ZDoom based ports before GZDoom 4.8 to set the compatmode to a certain preset without just manually setting the compatability flags.

**Comment by Youda008** [comment]
Ok, fixed in master, will be part of 1.6.1
