### ISSUE TITLE
1.6 issue with  with initial set up (i think so)

### ISSUE THREAD

**Issue by Aconee** [Youda008/DoomRunner#73]
sorry, after doing everything with new version 1.6 with initial set up, when you closed program and open it again, program start over with initial set up ,  even with tick on save globaly or others it always back with save globaly and i have to do it all over again and again

same goes with output options when tick on show fps, it only work once after you closed program then open it again and do the work over

sorry for my bad english and my communication, i have to use google translate sometime

thank you for making fps checker i really like the new output options with fps woo hoo

**Comment by Youda008** [comment]
Isn't it a problem with file permissions? Did you extract DoomRunner into Program Files? If yes, you need to do this
![obrazek](https://user-images.githubusercontent.com/20306543/191939687-e6c9241f-91cc-4b5f-a59c-f8c5dab11b95.png)

If no, try manually deleting `options.json` and start again.

**Comment by Aconee** [comment]
still can't do it, but if i copy options.json from 1.5.3 (while open 1.6 json file doens't appear) it work only with initial set up, and the output options is still uncheck if i closed program

**Comment by Youda008** [comment]
And it doesn't show any warning/error messages? Try running DoomRunner from cmd.exe if something isn't written there.

**Comment by Aconee** [comment]
yeah extracly sorry for late rely

**Comment by Youda008** [comment]
Exactly what? Can you show me screenshot? And maybe also send me the problematic options.json?

**Comment by Aconee** [comment]
hmm im sorry that my communicate isn't good, i think it's better to send you a video, hope you dont mind that

https://www.mediafire.com/file/4x516oquti91so3/2022-09-27_15-56-20.rar/file

**Comment by Zod1234** [comment]
i tried 1.6.1 and same issue.  launching from cmd showed no output.

**Comment by Youda008** [comment]
I think i found it. Sorry about that. Will be fixed soon.

**Comment by Aconee** [comment]
hey thanks

**Comment by Youda008** [comment]
Can you please confirm that this one works for you?
[DoomRunner.zip](https://github.com/Youda008/DoomRunner/files/9662982/DoomRunner.zip)

**Comment by Youda008** [comment]
Fixed and released. Hope it works now, it does for me.
