### ISSUE TITLE
[Possible Bug] Complevel in Crispy Heretic/Hexen (possibly also Crispy Strife)

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#74]
Weird things happen with the -complevel setting when switching ports. 

Example:
- I have set up Doom, Doom II, Plutonia and TNT to be run with Woof!
- Doom Complete is set up to be run with GZDoom
- Heretic and Hexen are to be run with Crispy Heretic/Crispy Hexen

I am setting up -complevel 4 for Plutonia through the launcher. If I go to Doom Complete now, it sets -compatmode 4. Heretic and Hexen (which don't support compatmodes/complevels) get +compatmode 4. If I check "Compatibility Level" in the "Launch" tab, it's empty and when switching back to Plutonia (where I made the setting in the first place), it's empty as well.

Is that expected behavior or am I supposed to remove the complevel settings before changing to another port? I think the problem is that it doesn't reset the complevel settings properly when switching to a title with a different port. 

Observations:
- You can reset complevels by switching to a different port for the same game where you initially made the complevel setup.
- As long as you stay with the same port, the launcher will apply the complevel to all titles (without clearing the "Compatibility Level" entry
- If you switch to a game that's using a different port, "Compatibility Level" is empty and it keeps the command line from the previous port (with adjustments, which are apparently not always right - probably also because the launcher doesn't know Crispy Heretic/Hexen/Strife)

**Comment by Youda008** [comment]
ffs, i just made a release 10 minutes ago

Can you record me a short video or gif of the bug?
I'm not sure i understand what you're describing.

**Comment by NightFright2k19** [comment]
I guess it is hard to understand if you don't have my kinda setup in front of you. I'll see if I can find a way to visualize it. At least with lots of screenshots if I can't figure out anything else.

**Comment by Youda008** [comment]
If you have any of the modern graphics cards, you must have either the AMD Radeon Adrenaline or NVidia ShadowPlay, they can record with a press of a keyboard shortcut.
If you have neither, OBS is a good alternative, although it's little more difficult to use.

**Comment by NightFright2k19** [comment]
Alright then. Here is a demo video with what I have described above. Hopefully, MP4 is an acceptable format for you (had to zip it since otherwise it would be too large for upload).

[complevel_demo.zip](https://github.com/Youda008/DoomRunner/files/9671569/complevel_demo.zip)

**Comment by Youda008** [comment]
Ah, ok, i see what you're trying to do.

First of all, do you use this option?
![obrazek](https://user-images.githubusercontent.com/20306543/192968336-1a302134-7022-49d8-814e-02084b826748.png)
Because otherwise the selected comp level is stored once for the whole launcher regardless of your selected preset or whatever.

Secondly, the compat level combo-box must be reset to <nothing selected> when an engine is changed to some that expects different parameter (`-complevel` vs `-compatmode`) than the previous one, because then the previous selected value is no longer valid, because different parameters have different possible values (-complevel 4 is not the same as -compatmode 4)

The bug here is that the reset is not complete. The combo-box is reset, but it stays on the command line. That's a little mystery for me, but i will figure that out.

**Comment by NightFright2k19** [comment]
OK, I had set it to "Save globally". When I change it to "Save to preset", it seems to be fixed. Anyway, it shouldn't behave like that with the other option.

**Comment by Youda008** [comment]
So, you're essentially asking to store the compat level in relation to the selected WAD? Am i correct?
Or you want it to be stored always in the Preset, regardless of the setting in Initial Setup?

**Comment by NightFright2k19** [comment]
I would say wad-based complevel saving would make the most sense to me, yeah. One way or the other, it wouldn't be depending on the "Save globally"/"Save to preset" selection any more, so it should be more robust in any case.

**Comment by Youda008** [comment]
I will have to think about this, because this would become yet another exception to the overall design.

**Comment by Youda008** [comment]
Can you please briefly test that this version doesn't break anything that was working before?
[DoomRunner-1.6.3-preview1.zip](https://github.com/Youda008/DoomRunner/files/9700925/DoomRunner-1.6.3-preview1.zip)
I would like to do one more bug-fix release before i start reworking the way Launch options are stored, to solve the original issue.

**Comment by NightFright2k19** [comment]
My browser doesn't let me download this because it claims the d/l contains a virus (maybe a false positive).

**Comment by NightFright2k19** [comment]
Seems to work as intended in the final release now. Thumbs up!

**Comment by Youda008** [comment]
Hello @NightFright2k19, i implemented an experimental feature that allows choosing different storage for individual option groups.

It works like this:
![new_feature](https://user-images.githubusercontent.com/20306543/195155012-8dd50e2d-f711-4bd0-9355-7dea62786060.png)

Does this fit your use-case better?

You can try a preview here:  [DoomRunner-1.7-experimental.zip](https://github.com/Youda008/DoomRunner/files/9758281/DoomRunner-1.7-experimental.zip)

The launcher got more complicated with this rework, so it is possible new bugs will arise.
