### ISSUE TITLE
[BUG] auto define save path doesn't compute name with illegal characters

### ISSUE THREAD

**Issue by ibin7777** [Youda008/DoomRunner#76]
![image](https://user-images.githubusercontent.com/64576479/194754727-0618a429-b970-4d3c-8c7b-4dc9e179b9a7.png)
As u see in the screenshot, I like to put a star symbol on presets that I most wanna play, that lead to a problem with 1.6 update on the function of "Use preset name as target directory"

You might could already guessed, it cannot generate folder for presets that contains the ⭐(or any other illegal characters). Resulting the preset not saving at all.

**Comment by Youda008** [comment]
Ufff 😅 I really did not expect anyone would do this.

**Comment by ibin7777** [comment]
> Ufff 😅 I really did not expect anyone would do this.

It's ok if that's too much of a hassle to fix, I'll just delete the stars, I can imagine not many people does what I do😂

**Comment by Youda008** [comment]
Actually now, when digging deep into it, it is allowed to use stars and other UTF-8 characters in directory names.
![obrazek](https://user-images.githubusercontent.com/20306543/194764079-d260ae89-cc0e-4f61-b168-602fbef82d3f.png)
So what exactly went wrong?

**Comment by Youda008** [comment]
Actually, seems working for me.
![obrazek](https://user-images.githubusercontent.com/20306543/194764371-e69ec11d-5c62-4633-86f7-d4661fd0d71d.png)

**Comment by Youda008** [comment]
Ok, it's the older engines that have problems with them. ZDoom, old GZDoom or PrBoom all failed to save a file with Unicode characters. I will rather remove them then.

**Comment by Youda008** [comment]
Should be fixed in 1.6.4
