### ISSUE TITLE
Glibc Error on Debian Stable

### ISSUE THREAD

**Issue by LinuxToasty** [Youda008/DoomRunner#78]
Linux version requires GLIBC_2.34 and Debian Stable (Bullseye) is at 2.31.
Might be worth mentioning on the Readme that you would have to compile from source on Debian Stable. 
Glibc is usually backwards compatible so versions compiled with 2.31 will also work in  Ubuntu LTS (2.35) and Arch (2.36)

**Comment by Youda008** [comment]
It kinda is mentioned here: https://github.com/Youda008/DoomRunner#Linux

If i find a way how to downgrade glibc without consequences and link against it, i will do it.
Alternatively, i can try linking it statically.

**Comment by LinuxToasty** [comment]
No problem. I doubt it is worth downgrading or statically linking for just this use case. 

Thought it may be worth a mention as not all users may be aware that Debian Stable and other distros based off of stable (LMDE/Devuan) etc may be aware that 22.04 uses newer libraries.
