### ISSUE TITLE
Preview of version 1.7 available for beta-testing

### ISSUE THREAD

**Issue by Youda008** [Youda008/DoomRunner#79]
I implemented an experimental feature and i would like to hear your opinions first before releasing it.

Previously you could control where some of the options get saved (into a preset or for the whole launcher) via this setting
![obrazek](https://user-images.githubusercontent.com/20306543/196046525-1a677fe6-0922-49ef-bf53-3c808434f98c.png)
but with this you can only chose it for all of the options on the second tab together, so if you wanted for example to have different compatibility level for each preset, you had to then set gameplay options also for each preset.

The new mechanism makes this choice more granular and allows to select it for each of the option groups separately. Here's an example:
![obrazek2](https://user-images.githubusercontent.com/20306543/195155012-8dd50e2d-f711-4bd0-9355-7dea62786060.png)

Would this improve the experience for you, or is it becomming too complicated?
And would you like to also choose storage for the Output Options or it makes no sense there?

Download here: [DoomRunner-1.7-preview-Windows-64bit-static.zip](https://github.com/Youda008/DoomRunner/files/9795185/DoomRunner-1.7-preview-Windows-64bit-static.zip)

**Comment by Aconee** [comment]
oh that great i will try 1.7 now, my 1.6.4 now getting error when open doom runner it say Error loading option : Loading options failed : illegal value

 Last night I still played normally, and this morning when I opened doom runner, it reported such an error
