### ISSUE TITLE
Extract map names from IWAD and feed them to "Launch selected map" combo box.

### ISSUE THREAD

**Issue by Youda008** [Youda008/DoomRunner#8]
Currently the content of the "Launch selected map" combo box is derived just from the IWAD file name. If it's Doom1, it fills it with E1M1, E1M2,... . In all other cases MAP01, MAP02, ...
Best option would be to look inside the IWAD file and extract the names from it.
If anyone knows the specification of the format of the IWAD files and can explain me how do i find those names, that would help me a lot.

**Comment by Caiuzx** [comment]
https://github.com/sirjuddington/SLADE
the name of the map is in the mapinfo
https://doom.fandom.com/wiki/MAPINFO
the structure of wad
https://doom.fandom.com/wiki/WAD

**Comment by Youda008** [comment]
Done. Will be part of next release.
