### ISSUE TITLE
[Suggestion] Keep entries for removed files

### ISSUE THREAD

**Issue by proydoha** [Youda008/DoomRunner#80]
I suggest keeping entries for removed files but display them as red and/or crossed out. And obviously do not include them in a final launch command.

The reason for this suggestion is that I keep losing my load orders because when I update my mod files I delete the old version and put a new one (usually with a different name) into the same folder. DoomRunner reports that file is missing and removes it from load order and I need to remember where exactly it was to replace it with a new version.

This is not a major issue when mod is only present in one preset but when it is present in a multiple ones that you may not select for a while it grows into a big problem. With entries for removed files still present I could easily drop new versions of files into same places of the load order and then remove broken ones manually.

**Comment by Youda008** [comment]
Hm, nice idea. Should be easy.

**Comment by Youda008** [comment]
Done. Will be part of 1.7
