### ISSUE TITLE
[Bug?] console output to external window causes deselection of IWAD and CFG.

### ISSUE THREAD

**Issue by ghostboy1225** [Youda008/DoomRunner#81]
Not quite sure if a bug or an intentional feature but when having the external window for console output it causes the IWAD directory to reload and deselect your last chosen IWAD while with console output to window disabled it doesn't. also seems to reset your cfg selection.

currently using windows 10 as an OS

sometime prior i had to delete my options file as it got corrupted somehow and was unable to save presets. (Windows 10 auto restarted is my suspicion)
not sure what else is useful info but let me know and i'll amend this post.

**Comment by Youda008** [comment]
Hm, i think i know why, but that's gonna be little tough to fix.

**Comment by Youda008** [comment]
Ok, that wasn't so hard. I will make 1.6.5 with this.

**Comment by NightFright2k19** [comment]
I also noticed that my GZDoom ini selection sometimes gets lost, but couldn't reliably reproduce it so far. Let's see if next version fixes it.

**Comment by Youda008** [comment]
Well logically, all paths become invalid when an engine is launched, because the engine needs to have a working directory set to itself, so everything that is automatically refreshed (IWADs, config files, save files, demo files) would get reset.
But that is now resolved.
