### ISSUE TITLE
[Feature] Support for Strife VE

### ISSUE THREAD

**Issue by NightFright2k19** [Youda008/DoomRunner#83]
The Strife Veteran Edition has a standalone version available on GOG.com which you can also use to launch it via DoomRunner. Since it is based on Chocolate Doom, it would be great if the launcher recognized its engine family directly.

Name of the executable: strife-ve.exe

**Comment by Youda008** [comment]
Ok, no problem.

**Comment by NightFright2k19** [comment]
That was fast! Thanks a lot!
