### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by lovilo** [Youda008/DoomRunner#84]
Hello, 

As of version 1.6 the DoomRunner.exe executable has a high cpu usage all the time it is open. Attached image: 

![image](https://user-images.githubusercontent.com/64167205/200106968-7b96b69f-b17b-4e46-9187-1622a877278f.png)

I have tested version 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4 and 1.7 beta. Same issue in all scenarios. Fresh install in all cases (no legacy config file) .

Greetings!

**Comment by Youda008** [comment]
Can you show me your setup? What are your directories for iwads, maps and mods? How many files are there aproximatelly etc?

**Comment by lovilo** [comment]
Hi! 

This is my setup: 

![image](https://user-images.githubusercontent.com/64167205/200413699-b10e7819-0e6e-4da9-90a3-9e36b6754599.png)

Engine folder --> 
![image](https://user-images.githubusercontent.com/64167205/200414049-4607b65e-05c7-41b5-a881-dd49861715f0.png)

iWads Folder --> 
![image](https://user-images.githubusercontent.com/64167205/200414108-d37818f5-07c4-4829-a2bb-487ffcdbd05d.png)

Maps Folder --> 
![image](https://user-images.githubusercontent.com/64167205/200414156-8f48172a-d0b7-459a-87bc-ff0a0ab1c6a6.png)

Mods Folder --> 
![image](https://user-images.githubusercontent.com/64167205/200414220-f1aae4fc-4607-4c24-bfc3-9533a1cce89f.png)

TC Folder --> 
![image](https://user-images.githubusercontent.com/64167205/200414262-bf548f3b-acea-4614-853e-15922dbddf27.png)


If I download the executable DoomRunner.exe and run it without any configuration (First time), it also happens. I attach an image: 
![image](https://user-images.githubusercontent.com/64167205/200414752-7d5274c0-9f03-44e2-ae44-7300ec977334.png)


Regards

**Comment by Contmotore** [comment]
Same here in Arch Linux

**Comment by Youda008** [comment]
I'm having troubles profiling the application, but i've noticed the CPU usage goes up, when i clear the map directory in Setup.

Can you please try entering something here (ideally some small directory with only few files)
![obrazek](https://user-images.githubusercontent.com/20306543/201491626-d62ad679-f153-4744-a721-0418c090e8e6.png)
and report back if the CPU usage goes away after clicking Done?

**Comment by lovilo** [comment]
Hello, 

I have this configuration: 

![image](https://user-images.githubusercontent.com/64167205/201512539-0c7801b3-917a-4dc9-9e9d-1fdb1293a4be.png)

The problem persists: 
![image](https://user-images.githubusercontent.com/64167205/201512562-3b56574b-2bff-47fa-aca9-502bd58915e6.png)

I try removing directory with maps and use absolute paths. Same result, high use cpu. 

Regards!

**Comment by Youda008** [comment]
I suspect 1 change that was added in 1.6. Can you please try 1.5.3 or older if it also happens there?

**Comment by Youda008** [comment]
1st attempt to fix is in the recent release.

**Comment by lovilo** [comment]
Hi! 

I just tested it and now I no longer have the incident. It looks like you have found the solution! 

Thank you!
