### ISSUE TITLE
Selecting a different version of GZDoom will launch the first one

### ISSUE THREAD

**Issue by wolfmanfp** [Youda008/DoomRunner#85]
Greetings,
I have three different versions of GZDoom set up in DoomRunner: 4.8.2, a devbuild, and the recent 4.9.0. The first one is in the same folder as DR, the two other versions are in subfolders.
If I select the other two versions, DR launches 4.8.2 instead. It only works as intended if I rename the two other executables as `gzdoom-dev.exe` and `gzdoom-4.9.0.exe`.

**Comment by Youda008** [comment]
Can you please screenshot me the exact directory stucture where i can see where the executables are located?
And can you also send me your options.json?

**Comment by wolfmanfp** [comment]
Sure.
![Képernyőkép 2022-11-06 233624](https://user-images.githubusercontent.com/10774794/200198970-5e768082-7d81-438d-91eb-2b71fd918afb.png)
[options.zip](https://github.com/Youda008/DoomRunner/files/9946994/options.zip)

**Comment by wolfmanfp** [comment]
I forgot to mention, I'm currently using the latest stable version. Launching different GZDoom versions worked correctly in 1.5.

**Comment by Youda008** [comment]
So apparently this is a Windows feature https://superuser.com/a/1683394/401036, it searches in the parent process directory first and only if not found it looks into current directory.

Luckily there is a simple workaround.

**Comment by Youda008** [comment]
Should be fixed.

**Comment by wolfmanfp** [comment]
Just tried 1.6.5 and it works now. Thank you!
