### ISSUE TITLE
Crash-to-desktop when selecting DeHackEd/BEX file

### ISSUE THREAD

**Issue by j-martina** [Youda008/DoomRunner#87]
In the map pack selection dialog, clicking on one of the text-type lumps (.deh or .bex extension) immediately causes a terminate.

At Sources/DoomUtils.cpp, line 134 (tested on 88316ed, the current commit at time of writing) a `bad_alloc` exception gets thrown. I tested this with cchest3.bex (Community Chest 3) and the following statement:

```cxx
std::unique_ptr< LumpEntry [] > lumpDir( new LumpEntry [header.numLumps] );
```

passes in a value of 1766203496 under `header.numLumps`. I haven't started looking too deeply into whether DeHackEd is supposed to be handled like other WADs in case this one is already under investigation or fixed locally, but I also didn't see this reported here or on the ZDoom forum so I thought I'd make sure at least someone raised the alarm on it.

**Comment by Youda008** [comment]
Thanks for reporting. Pitty that you didn't say it 2 days earlier, the fix could have been already released.

**Comment by j-martina** [comment]
I've only been playing through WADs that either lack DeHackEd or come with it integrated, so I've missed it up until this point. I'm just glad I got this one in before the 1.7 release.

**Comment by Youda008** [comment]
Fixed and released.
