### ISSUE TITLE
[Inconsistency] Decrementing the custom number for Skill below 6 forces custom number back to Nightmare

### ISSUE THREAD

**Issue by Berzasperd** [Youda008/DoomRunner#88]
![doomrunner_customskillissue](https://user-images.githubusercontent.com/71313143/202291829-439b7956-559a-47d2-af89-a9c6b6814a76.png)

A minor issue, but to elaborate on the title, if you are changing the Skill level number by using the "custom number..." option in the "Gameplay" section on the "Launch options" tab (or "More options" tab in beta), setting the number in the text + up/down button field to a value below 6 will simultaneously disable (i.e. make non-interactive) the custom number text field and revert the Skill dropdown selector to the difficulty associated with that number.  This issue is caused by the fact that the named skill options in the dropdown menu disable the custom number text field and "custom number..." is the only one that enables it.  Changing the number in that field to one that is below 6 will automatically change the dropdown menu to a different skill, thus disabling the field.

Examples:

Changing the custom skill number from 6 to 5 by clicking the down arrow will change "custom number..." to "Nightmare" and disabled the buttons for the custom skill numbers.
Entering a number into the custom skill number field that is lower than 6 will disable the field and change "custom number..." to the associated skill level automatically, e.g. replacing 6 with 3 will set it to "Hurt me plenty"
The above examples apply if you use your mouse scroll wheel to change the numbers, as both the dropdown menu for skills and the custom number field can be changed using the scroll wheel.

Why is this an issue?  Under normal use cases, it probably isn't.  This is just a very minor consistency issue with the interface that I found that could use a little tweaking.  What is happening is that when trying to quickly change certain options using the scroll wheel, there is this one field that suddenly becomes inactive at an arbitrary point and it requires you to move out of the field and edit another field before you can continue.  The skill selection fields are notable in this case because you scroll down to increase difficulty using the dropdown menu ("I'm too young to die" -> "Nightmare") but you scroll up to increase the custom number to "higher" difficulty numbers.  The dropdown menu is styled after the in-game difficulty selection, so I wouldn't want that to change.

One oddity that is related to this issue is that the text field for custom numbers will get selected or highlighted (as if you used Ctrl + A) until the skill dropdown menu is modified twice or you enter and exit a separate window.  This happens if you use the scroll wheel to change the number or click the down arrow to decrement it, but not if you type in a number using the keyboard.  This seems to be related to how the buttons and scroll wheel inputs automatically "select" the associated fields.

Proposal 1: Allow the custom number option for skill accept arbitrarily low numbers (less than 6) and pass the appropriate -skill argument without being disabled or changing itself back to other difficulties.  This would allow you to scroll up and down freely in the text field the same way you can with the dropdown menu.

Proposal 2: Always enable the text field and keep the number to skill name association in effect.  This would keep the identities of the skill numbers with the names that represent them in game.  Numbers 6 and above would therefore need  to set the dropdown menu to "custom number..." automatically in the same fashion as numbers below 6 already do.

I believe either proposal would work equally well, but I am leaning towards Proposal 2 as being slightly better for the average user, simply because it makes it clear that those skill numbers are already used by the game itself.

**Comment by Youda008** [comment]
It's not a bug, i kinda designed it to work like this.
But i accept your explanation why it can be problematic, so if i don't run into a problem, i will change this.

**Comment by Youda008** [comment]
Done and released.
