### ISSUE TITLE
Multiple item select in mod list bug

### ISSUE THREAD

**Issue by siteod** [Youda008/DoomRunner#9]
I did a control+a in the mod list, but apparently that's not supposed to be allowed

![multiselectbug](https://user-images.githubusercontent.com/43916024/65067842-e892b900-d933-11e9-8e36-c606fbfc3b11.JPG)

**Comment by Youda008** [comment]
Oops. Did not think about these special shortcuts.

**Comment by Youda008** [comment]
I cannot reproduce it. I pressed CTRL+A and selected all items, but this error did not appear. What else do i need to do after selecting all to make this happen?

**Comment by Youda008** [comment]
Fixed in 1.1.
