### ISSUE TITLE
Hyperlink in "Update available" dialog box needs new color code

### ISSUE THREAD

**Issue by Berzasperd** [Youda008/DoomRunner#92]
I feel bad for not thinking about this before, but now that the update checker has the dark theme colors, it's hyperlink needs the same code that fixes the colors for the About dialog hyperlinks.

![doomrunner_updatescreen](https://user-images.githubusercontent.com/71313143/204888409-3b1bf335-7c6f-4d5e-a997-e659a44863a1.png)

I was looking around the source code trying to see if it was something that could be copy and pasted over, but it is a little bit over my head for right now.  The closest thing I found to something related to the issue was these two lines here.

https://github.com/Youda008/DoomRunner/blob/698a2831cb3c43e4e425192a14d95621f97a9431/Sources/UpdateChecker.cpp#L35
https://github.com/Youda008/DoomRunner/blob/698a2831cb3c43e4e425192a14d95621f97a9431/Sources/UpdateChecker.cpp#L36

This was based on what you had said before, about how each hyperlink was being generated with that specific code and that it would have to be overridden for each one to fix it.  Hopefully I'm not just sending you on a wild goose chase with that.  Either way, this is a tiny issue that can be fixed whenever is convenient for you.  If I have some spare time, I might try to figure out compiling new code and/or making a pull request.

**Comment by Youda008** [comment]
fixed
