### ISSUE TITLE
[Feature] A Postman-like way of working with launch parameters

### ISSUE THREAD

**Issue by proydoha** [Youda008/DoomRunner#94]
Here's how Postman's 'Headers' tab looks like:
![image](https://user-images.githubusercontent.com/44492748/210810444-f414d4be-2bdc-4238-9ae3-2f831e064495.png)

You can add new headers by filling key-value fields but most importantly you can turn them on and off with a checkbox
It would be great if there was a launch parameter manager like Add Mods window but for parameters, like this:
![image](https://user-images.githubusercontent.com/44492748/210820467-ffffce9d-1c6a-46d4-a58d-32facc030b61.png)

Maybe it is worth making it collapsible with a button to make it hidden by default.
Maybe it is worth populating it with grayed out parameters taken from 'more options' tab that can't be checked off if they were checked on in 'More options'.

**Comment by Youda008** [comment]
May i know why the current checkboxes at the other tabs are not enough?
What other options do you frequently use?

**Comment by proydoha** [comment]
Other tabs are saved globally, not per profile and is very inconvenient because it is another tab.

Especially when multiplayer is involved. Currently I have this line for loading multiplayer HDest game for example:
`-host 2 +hdskill_normal +dmflags 2097152 +hd_pof 1 +teamdamage 1 +hd_safelifts false +hd_skin bubblyhelmet -loadgame "Save/save1.zds"`

But also I have whole different profile set up just to host it without loading the game:
`-host 2 +hdskill_normal +map map01 +hd_skin bubblyhelmet +dmflags 2097152 +hd_pof 1 +teamdamage 1`

And for joining if I want to quickly check something before I'll call friends to play it:
`-join localhost +hd_skin bubblyhelmet -loadgame "Save/save1.zds"`

The options that I use frequently are:
`-nomonsters`, `-loadgame`, `-host`, `-join`
`+skill`, `+map`, `+warp`, `+logfile`

**Comment by Youda008** [comment]
Since 1.7 you can go to "Menu" -> "Configure options storage" and select how those options are saved.

I understand that having to switch between tabs is more clicks, but i cannot fit everything onto the first tab.
Users with smaller monitors on Linux were already complaining that the launcher did not fit into their 1280x720 screens so i had to split the options into more tabs.
Also when i tried this approach with everything on a single tab very early, some people told me they would not use such launcher because it looked too complicated.

**Comment by Youda008** [comment]
Not exactly as you requested in your screenshot, but with the new version, you will be able to do what you want.

![add cmd arg](https://github.com/Youda008/DoomRunner/assets/20306543/077f6865-d63a-48d5-9f10-c71386c1cb0d)

**Comment by proydoha** [comment]
This looks amazing, thank you!
Will try it out soon!
