### ISSUE TITLE
Port/wad sensing

### ISSUE THREAD

**Issue by Yuraconst** [Youda008/DoomRunner#98]
Expected behavior:
port and IWAD detected right away

what I've got:
still get the setup prompt for the IWAD dir and no prompt at all for the port, rendering it unusable.
Also, port's auxilliary WAD/PK3 files are being shown where they shouldn't!

**Comment by Youda008** [comment]
I'm sorry but i don't understand you. Can you please describe it differently or maybe include a screenshot?

**Comment by Youda008** [comment]
Closing for not enough info given.
