### ISSUE TITLE
failure to parse options.json

### ISSUE THREAD

**Issue by Jokakun** [Youda008/DoomRunner#99]
What i do to solve this? Im using 1.7.1

**Comment by Youda008** [comment]
Can you please screenshot me the exact error message and can you upload here the `options.json` file?

**Comment by Jokakun** [comment]
[options.zip](https://github.com/Youda008/DoomRunner/files/11023801/options.zip)

**Comment by Jokakun** [comment]
I deleted it and everything seems ok, but since you wanted to view the file I retrieved it from my trash bin and showed you.

**Comment by Youda008** [comment]
Hm, the file was apparently corrupted during saving. This is a known but tricky issue. Hopefully i'll be able to solve this in the next version.
Btw, did you get a bluescreen or power outage before this happened?

**Comment by Jokakun** [comment]
Well, good luck for the next version then. I did not experience any kind of bluescreen/power outage as well.

**Comment by Youda008** [comment]
I have reduced the frequency of writing to file, by making it write the content only when something has changed. Hopefully that will solve your issue.
